// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateKeyResponse create key response
//
// swagger:model createKeyResponse
type CreateKeyResponse struct {

	// 密钥别名
	// Example: my-encryption-key
	Alias string `json:"alias,omitempty"`

	// created at
	// Example: 2025-11-26T10:00:00Z
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// 密钥描述
	Description string `json:"description,omitempty"`

	// 密钥ID
	// Example: key-1234567890abcdef
	// Required: true
	KeyID *string `json:"key_id"`

	// key state
	// Example: Enabled
	// Required: true
	// Enum: [Enabled Disabled PendingDeletion Deleted]
	KeyState *string `json:"key_state"`

	// key type
	// Example: AES_256
	// Required: true
	KeyType *string `json:"key_type"`

	// tags
	Tags map[string]string `json:"tags,omitempty"`

	// updated at
	// Example: 2025-11-26T10:00:00Z
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this create key response
func (m *CreateKeyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateKeyResponse) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CreateKeyResponse) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

var createKeyResponseTypeKeyStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Enabled","Disabled","PendingDeletion","Deleted"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createKeyResponseTypeKeyStatePropEnum = append(createKeyResponseTypeKeyStatePropEnum, v)
	}
}

const (

	// CreateKeyResponseKeyStateEnabled captures enum value "Enabled"
	CreateKeyResponseKeyStateEnabled string = "Enabled"

	// CreateKeyResponseKeyStateDisabled captures enum value "Disabled"
	CreateKeyResponseKeyStateDisabled string = "Disabled"

	// CreateKeyResponseKeyStatePendingDeletion captures enum value "PendingDeletion"
	CreateKeyResponseKeyStatePendingDeletion string = "PendingDeletion"

	// CreateKeyResponseKeyStateDeleted captures enum value "Deleted"
	CreateKeyResponseKeyStateDeleted string = "Deleted"
)

// prop value enum
func (m *CreateKeyResponse) validateKeyStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createKeyResponseTypeKeyStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateKeyResponse) validateKeyState(formats strfmt.Registry) error {

	if err := validate.Required("key_state", "body", m.KeyState); err != nil {
		return err
	}

	// value enum
	if err := m.validateKeyStateEnum("key_state", "body", *m.KeyState); err != nil {
		return err
	}

	return nil
}

func (m *CreateKeyResponse) validateKeyType(formats strfmt.Registry) error {

	if err := validate.Required("key_type", "body", m.KeyType); err != nil {
		return err
	}

	return nil
}

func (m *CreateKeyResponse) validateUpdatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create key response based on context it is used
func (m *CreateKeyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateKeyResponse) UnmarshalBinary(b []byte) error {
	var res CreateKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
