// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetAuditLogsResponse get audit logs response
//
// swagger:model getAuditLogsResponse
type GetAuditLogsResponse struct {

	// events
	// Required: true
	Events []*GetAuditLogsResponseEventsItems0 `json:"events"`

	// total
	// Example: 100
	Total int64 `json:"total,omitempty"`
}

// Validate validates this get audit logs response
func (m *GetAuditLogsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEvents(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetAuditLogsResponse) validateEvents(formats strfmt.Registry) error {

	if err := validate.Required("events", "body", m.Events); err != nil {
		return err
	}

	for i := 0; i < len(m.Events); i++ {
		if swag.IsZero(m.Events[i]) { // not required
			continue
		}

		if m.Events[i] != nil {
			if err := m.Events[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("events" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("events" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get audit logs response based on the context it is used
func (m *GetAuditLogsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEvents(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetAuditLogsResponse) contextValidateEvents(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Events); i++ {

		if m.Events[i] != nil {
			if err := m.Events[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("events" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("events" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetAuditLogsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAuditLogsResponse) UnmarshalBinary(b []byte) error {
	var res GetAuditLogsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// GetAuditLogsResponseEventsItems0 get audit logs response events items0
//
// swagger:model GetAuditLogsResponseEventsItems0
type GetAuditLogsResponseEventsItems0 struct {

	// details
	Details interface{} `json:"details,omitempty"`

	// event type
	// Example: KeyCreated
	// Required: true
	EventType *string `json:"event_type"`

	// ip address
	// Example: 192.168.1.1
	IPAddress string `json:"ip_address,omitempty"`

	// key id
	// Example: key-1234567890abcdef
	KeyID string `json:"key_id,omitempty"`

	// operation
	// Example: create_key
	// Required: true
	Operation *string `json:"operation"`

	// result
	// Example: Success
	// Required: true
	// Enum: [Success Failed]
	Result *string `json:"result"`

	// timestamp
	// Example: 2025-11-26T10:00:00Z
	// Required: true
	// Format: date-time
	Timestamp *strfmt.DateTime `json:"timestamp"`

	// user id
	// Example: user-123
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this get audit logs response events items0
func (m *GetAuditLogsResponseEventsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOperation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetAuditLogsResponseEventsItems0) validateEventType(formats strfmt.Registry) error {

	if err := validate.Required("event_type", "body", m.EventType); err != nil {
		return err
	}

	return nil
}

func (m *GetAuditLogsResponseEventsItems0) validateOperation(formats strfmt.Registry) error {

	if err := validate.Required("operation", "body", m.Operation); err != nil {
		return err
	}

	return nil
}

var getAuditLogsResponseEventsItems0TypeResultPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Success","Failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getAuditLogsResponseEventsItems0TypeResultPropEnum = append(getAuditLogsResponseEventsItems0TypeResultPropEnum, v)
	}
}

const (

	// GetAuditLogsResponseEventsItems0ResultSuccess captures enum value "Success"
	GetAuditLogsResponseEventsItems0ResultSuccess string = "Success"

	// GetAuditLogsResponseEventsItems0ResultFailed captures enum value "Failed"
	GetAuditLogsResponseEventsItems0ResultFailed string = "Failed"
)

// prop value enum
func (m *GetAuditLogsResponseEventsItems0) validateResultEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getAuditLogsResponseEventsItems0TypeResultPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GetAuditLogsResponseEventsItems0) validateResult(formats strfmt.Registry) error {

	if err := validate.Required("result", "body", m.Result); err != nil {
		return err
	}

	// value enum
	if err := m.validateResultEnum("result", "body", *m.Result); err != nil {
		return err
	}

	return nil
}

func (m *GetAuditLogsResponseEventsItems0) validateTimestamp(formats strfmt.Registry) error {

	if err := validate.Required("timestamp", "body", m.Timestamp); err != nil {
		return err
	}

	if err := validate.FormatOf("timestamp", "body", "date-time", m.Timestamp.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get audit logs response events items0 based on context it is used
func (m *GetAuditLogsResponseEventsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetAuditLogsResponseEventsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAuditLogsResponseEventsItems0) UnmarshalBinary(b []byte) error {
	var res GetAuditLogsResponseEventsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
