// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostSignPayload post sign payload
//
// swagger:model postSignPayload
type PostSignPayload struct {

	// 签名算法
	// Example: ECDSA_SHA256
	// Required: true
	// Enum: [ECDSA_SHA256 ECDSA_SHA384 ECDSA_SHA512 ED25519]
	Algorithm *string `json:"algorithm"`

	// 密钥ID
	// Example: key-1234567890abcdef
	// Required: true
	KeyID *string `json:"key_id"`

	// 消息数据（base64编码）
	// Example: SGVsbG8gV29ybGQ=
	// Required: true
	// Format: byte
	Message *strfmt.Base64 `json:"message"`

	// 签名模式（RAW=原始数据，DIGEST=消息摘要）
	// Example: DIGEST
	// Enum: [RAW DIGEST]
	Mode *string `json:"mode,omitempty"`
}

// Validate validates this post sign payload
func (m *PostSignPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlgorithm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postSignPayloadTypeAlgorithmPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ECDSA_SHA256","ECDSA_SHA384","ECDSA_SHA512","ED25519"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postSignPayloadTypeAlgorithmPropEnum = append(postSignPayloadTypeAlgorithmPropEnum, v)
	}
}

const (

	// PostSignPayloadAlgorithmECDSASHA256 captures enum value "ECDSA_SHA256"
	PostSignPayloadAlgorithmECDSASHA256 string = "ECDSA_SHA256"

	// PostSignPayloadAlgorithmECDSASHA384 captures enum value "ECDSA_SHA384"
	PostSignPayloadAlgorithmECDSASHA384 string = "ECDSA_SHA384"

	// PostSignPayloadAlgorithmECDSASHA512 captures enum value "ECDSA_SHA512"
	PostSignPayloadAlgorithmECDSASHA512 string = "ECDSA_SHA512"

	// PostSignPayloadAlgorithmED25519 captures enum value "ED25519"
	PostSignPayloadAlgorithmED25519 string = "ED25519"
)

// prop value enum
func (m *PostSignPayload) validateAlgorithmEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postSignPayloadTypeAlgorithmPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostSignPayload) validateAlgorithm(formats strfmt.Registry) error {

	if err := validate.Required("algorithm", "body", m.Algorithm); err != nil {
		return err
	}

	// value enum
	if err := m.validateAlgorithmEnum("algorithm", "body", *m.Algorithm); err != nil {
		return err
	}

	return nil
}

func (m *PostSignPayload) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

func (m *PostSignPayload) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

var postSignPayloadTypeModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["RAW","DIGEST"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postSignPayloadTypeModePropEnum = append(postSignPayloadTypeModePropEnum, v)
	}
}

const (

	// PostSignPayloadModeRAW captures enum value "RAW"
	PostSignPayloadModeRAW string = "RAW"

	// PostSignPayloadModeDIGEST captures enum value "DIGEST"
	PostSignPayloadModeDIGEST string = "DIGEST"
)

// prop value enum
func (m *PostSignPayload) validateModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postSignPayloadTypeModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostSignPayload) validateMode(formats strfmt.Registry) error {
	if swag.IsZero(m.Mode) { // not required
		return nil
	}

	// value enum
	if err := m.validateModeEnum("mode", "body", *m.Mode); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post sign payload based on context it is used
func (m *PostSignPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostSignPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostSignPayload) UnmarshalBinary(b []byte) error {
	var res PostSignPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
