// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostVerifyPayload post verify payload
//
// swagger:model postVerifyPayload
type PostVerifyPayload struct {

	// 签名算法
	// Example: ECDSA_SHA256
	// Required: true
	// Enum: [ECDSA_SHA256 ECDSA_SHA384 ECDSA_SHA512 ED25519]
	Algorithm *string `json:"algorithm"`

	// 密钥ID
	// Example: key-1234567890abcdef
	// Required: true
	KeyID *string `json:"key_id"`

	// 消息数据（base64编码）
	// Example: SGVsbG8gV29ybGQ=
	// Required: true
	// Format: byte
	Message *strfmt.Base64 `json:"message"`

	// 签名模式
	// Example: DIGEST
	// Enum: [RAW DIGEST]
	Mode *string `json:"mode,omitempty"`

	// 签名数据（base64编码）
	// Example: MEUCIQDxHqXjF3Z8K9L2M1N4O5P6Q7R8S9T0U1V2W3X4Y5Z6A7B8C9D0E1F2G3H4I5J6K7L8M9N0O1P2Q3R4S5T6U7V8W9X0Y1Z2A3B4C5D6E7F8G9H0I1J2K3L4M5N6O7P8Q9R0S1T2U3V4W5X6Y7Z8A9B0C1D2E3F4G5H6I7J8K9L0M1N2O3P4Q5R6S7T8U9V0W1X2Y3Z4A5B6C7D8E9F0G1H2I3J4K5L6M7N8O9P0Q1R2S3T4U5V6W7X8Y9Z0
	// Required: true
	// Format: byte
	Signature *strfmt.Base64 `json:"signature"`
}

// Validate validates this post verify payload
func (m *PostVerifyPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlgorithm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postVerifyPayloadTypeAlgorithmPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ECDSA_SHA256","ECDSA_SHA384","ECDSA_SHA512","ED25519"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postVerifyPayloadTypeAlgorithmPropEnum = append(postVerifyPayloadTypeAlgorithmPropEnum, v)
	}
}

const (

	// PostVerifyPayloadAlgorithmECDSASHA256 captures enum value "ECDSA_SHA256"
	PostVerifyPayloadAlgorithmECDSASHA256 string = "ECDSA_SHA256"

	// PostVerifyPayloadAlgorithmECDSASHA384 captures enum value "ECDSA_SHA384"
	PostVerifyPayloadAlgorithmECDSASHA384 string = "ECDSA_SHA384"

	// PostVerifyPayloadAlgorithmECDSASHA512 captures enum value "ECDSA_SHA512"
	PostVerifyPayloadAlgorithmECDSASHA512 string = "ECDSA_SHA512"

	// PostVerifyPayloadAlgorithmED25519 captures enum value "ED25519"
	PostVerifyPayloadAlgorithmED25519 string = "ED25519"
)

// prop value enum
func (m *PostVerifyPayload) validateAlgorithmEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postVerifyPayloadTypeAlgorithmPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostVerifyPayload) validateAlgorithm(formats strfmt.Registry) error {

	if err := validate.Required("algorithm", "body", m.Algorithm); err != nil {
		return err
	}

	// value enum
	if err := m.validateAlgorithmEnum("algorithm", "body", *m.Algorithm); err != nil {
		return err
	}

	return nil
}

func (m *PostVerifyPayload) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

func (m *PostVerifyPayload) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

var postVerifyPayloadTypeModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["RAW","DIGEST"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postVerifyPayloadTypeModePropEnum = append(postVerifyPayloadTypeModePropEnum, v)
	}
}

const (

	// PostVerifyPayloadModeRAW captures enum value "RAW"
	PostVerifyPayloadModeRAW string = "RAW"

	// PostVerifyPayloadModeDIGEST captures enum value "DIGEST"
	PostVerifyPayloadModeDIGEST string = "DIGEST"
)

// prop value enum
func (m *PostVerifyPayload) validateModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postVerifyPayloadTypeModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostVerifyPayload) validateMode(formats strfmt.Registry) error {
	if swag.IsZero(m.Mode) { // not required
		return nil
	}

	// value enum
	if err := m.validateModeEnum("mode", "body", *m.Mode); err != nil {
		return err
	}

	return nil
}

func (m *PostVerifyPayload) validateSignature(formats strfmt.Registry) error {

	if err := validate.Required("signature", "body", m.Signature); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post verify payload based on context it is used
func (m *PostVerifyPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostVerifyPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostVerifyPayload) UnmarshalBinary(b []byte) error {
	var res PostVerifyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
