// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostGenerateDataKeyPayload post generate data key payload
//
// swagger:model postGenerateDataKeyPayload
type PostGenerateDataKeyPayload struct {

	// 加密上下文（可选）
	EncryptionContext map[string]string `json:"encryption_context,omitempty"`

	// 密钥ID（KEK）
	// Example: key-1234567890abcdef
	// Required: true
	KeyID *string `json:"key_id"`

	// 数据密钥规格
	// Example: AES_256
	// Enum: [AES_256]
	KeySpec string `json:"key_spec,omitempty"`

	// 数据密钥长度（字节）
	// Example: 32
	NumberOfBytes int64 `json:"number_of_bytes,omitempty"`

	// 是否返回明文数据密钥
	// Example: true
	ReturnPlaintext *bool `json:"return_plaintext,omitempty"`
}

// Validate validates this post generate data key payload
func (m *PostGenerateDataKeyPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeySpec(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostGenerateDataKeyPayload) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

var postGenerateDataKeyPayloadTypeKeySpecPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AES_256"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postGenerateDataKeyPayloadTypeKeySpecPropEnum = append(postGenerateDataKeyPayloadTypeKeySpecPropEnum, v)
	}
}

const (

	// PostGenerateDataKeyPayloadKeySpecAES256 captures enum value "AES_256"
	PostGenerateDataKeyPayloadKeySpecAES256 string = "AES_256"
)

// prop value enum
func (m *PostGenerateDataKeyPayload) validateKeySpecEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postGenerateDataKeyPayloadTypeKeySpecPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostGenerateDataKeyPayload) validateKeySpec(formats strfmt.Registry) error {
	if swag.IsZero(m.KeySpec) { // not required
		return nil
	}

	// value enum
	if err := m.validateKeySpecEnum("key_spec", "body", m.KeySpec); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post generate data key payload based on context it is used
func (m *PostGenerateDataKeyPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostGenerateDataKeyPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostGenerateDataKeyPayload) UnmarshalBinary(b []byte) error {
	var res PostGenerateDataKeyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
