// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCreateKeyPayload post create key payload
//
// swagger:model postCreateKeyPayload
type PostCreateKeyPayload struct {

	// 密钥别名
	// Example: my-encryption-key
	Alias string `json:"alias,omitempty"`

	// 密钥描述
	// Example: 用于生产环境数据加密
	Description string `json:"description,omitempty"`

	// key spec
	KeySpec *PostCreateKeyPayloadKeySpec `json:"key_spec,omitempty"`

	// 密钥类型
	// Example: AES_256
	// Required: true
	// Enum: [ECC_SECP256K1 ECC_P256 ED25519 AES_256]
	KeyType *string `json:"key_type"`

	// 策略ID
	// Example: policy-123
	PolicyID string `json:"policy_id,omitempty"`

	// 标签
	// Example: {"environment":"production","team":"backend"}
	Tags map[string]string `json:"tags,omitempty"`
}

// Validate validates this post create key payload
func (m *PostCreateKeyPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeySpec(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCreateKeyPayload) validateKeySpec(formats strfmt.Registry) error {
	if swag.IsZero(m.KeySpec) { // not required
		return nil
	}

	if m.KeySpec != nil {
		if err := m.KeySpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("key_spec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("key_spec")
			}
			return err
		}
	}

	return nil
}

var postCreateKeyPayloadTypeKeyTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ECC_SECP256K1","ECC_P256","ED25519","AES_256"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postCreateKeyPayloadTypeKeyTypePropEnum = append(postCreateKeyPayloadTypeKeyTypePropEnum, v)
	}
}

const (

	// PostCreateKeyPayloadKeyTypeECCSECP256K1 captures enum value "ECC_SECP256K1"
	PostCreateKeyPayloadKeyTypeECCSECP256K1 string = "ECC_SECP256K1"

	// PostCreateKeyPayloadKeyTypeECCP256 captures enum value "ECC_P256"
	PostCreateKeyPayloadKeyTypeECCP256 string = "ECC_P256"

	// PostCreateKeyPayloadKeyTypeED25519 captures enum value "ED25519"
	PostCreateKeyPayloadKeyTypeED25519 string = "ED25519"

	// PostCreateKeyPayloadKeyTypeAES256 captures enum value "AES_256"
	PostCreateKeyPayloadKeyTypeAES256 string = "AES_256"
)

// prop value enum
func (m *PostCreateKeyPayload) validateKeyTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postCreateKeyPayloadTypeKeyTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostCreateKeyPayload) validateKeyType(formats strfmt.Registry) error {

	if err := validate.Required("key_type", "body", m.KeyType); err != nil {
		return err
	}

	// value enum
	if err := m.validateKeyTypeEnum("key_type", "body", *m.KeyType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this post create key payload based on the context it is used
func (m *PostCreateKeyPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateKeySpec(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCreateKeyPayload) contextValidateKeySpec(ctx context.Context, formats strfmt.Registry) error {

	if m.KeySpec != nil {
		if err := m.KeySpec.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("key_spec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("key_spec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostCreateKeyPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCreateKeyPayload) UnmarshalBinary(b []byte) error {
	var res PostCreateKeyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PostCreateKeyPayloadKeySpec post create key payload key spec
//
// swagger:model PostCreateKeyPayloadKeySpec
type PostCreateKeyPayloadKeySpec struct {

	// algorithm
	// Example: AES
	Algorithm string `json:"algorithm,omitempty"`

	// attributes
	Attributes map[string]string `json:"attributes,omitempty"`

	// curve
	// Example: P-256
	Curve string `json:"curve,omitempty"`

	// key size
	// Example: 256
	KeySize int64 `json:"key_size,omitempty"`
}

// Validate validates this post create key payload key spec
func (m *PostCreateKeyPayloadKeySpec) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post create key payload key spec based on context it is used
func (m *PostCreateKeyPayloadKeySpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostCreateKeyPayloadKeySpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCreateKeyPayloadKeySpec) UnmarshalBinary(b []byte) error {
	var res PostCreateKeyPayloadKeySpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
