// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostGenerateDataKeyResponse post generate data key response
//
// swagger:model postGenerateDataKeyResponse
type PostGenerateDataKeyResponse struct {

	// 加密的数据密钥（base64编码）
	// Example: eyJrZXlfaWQiOiJrZXktMTIzNDU2Nzg5MGFiY2RlZiIsInZlcnNpb24iOjEsImNpcGhlcnRleHQiOiIuLi4ifQ==
	// Required: true
	// Format: byte
	CiphertextBlob *strfmt.Base64 `json:"ciphertext_blob"`

	// key id
	// Example: key-1234567890abcdef
	// Required: true
	KeyID *string `json:"key_id"`

	// 明文数据密钥（base64编码，仅当return_plaintext=true时返回）
	// Example: SGVsbG8gV29ybGQ=
	// Format: byte
	Plaintext strfmt.Base64 `json:"plaintext,omitempty"`
}

// Validate validates this post generate data key response
func (m *PostGenerateDataKeyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCiphertextBlob(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostGenerateDataKeyResponse) validateCiphertextBlob(formats strfmt.Registry) error {

	if err := validate.Required("ciphertext_blob", "body", m.CiphertextBlob); err != nil {
		return err
	}

	return nil
}

func (m *PostGenerateDataKeyResponse) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post generate data key response based on context it is used
func (m *PostGenerateDataKeyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostGenerateDataKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostGenerateDataKeyResponse) UnmarshalBinary(b []byte) error {
	var res PostGenerateDataKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
