// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostEncryptPayload post encrypt payload
//
// swagger:model postEncryptPayload
type PostEncryptPayload struct {

	// 加密上下文（可选）
	// Example: {"environment":"production","purpose":"database-encryption"}
	EncryptionContext map[string]string `json:"encryption_context,omitempty"`

	// 密钥ID
	// Example: key-1234567890abcdef
	// Required: true
	KeyID *string `json:"key_id"`

	// 明文数据（base64编码）
	// Example: SGVsbG8gV29ybGQ=
	// Required: true
	// Format: byte
	Plaintext *strfmt.Base64 `json:"plaintext"`
}

// Validate validates this post encrypt payload
func (m *PostEncryptPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlaintext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostEncryptPayload) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

func (m *PostEncryptPayload) validatePlaintext(formats strfmt.Registry) error {

	if err := validate.Required("plaintext", "body", m.Plaintext); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post encrypt payload based on context it is used
func (m *PostEncryptPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostEncryptPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostEncryptPayload) UnmarshalBinary(b []byte) error {
	var res PostEncryptPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
