// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDecryptPayload post decrypt payload
//
// swagger:model postDecryptPayload
type PostDecryptPayload struct {

	// 密文数据（base64编码）
	// Example: eyJrZXlfaWQiOiJrZXktMTIzNDU2Nzg5MGFiY2RlZiIsInZlcnNpb24iOjEsImNpcGhlcnRleHQiOiIuLi4ifQ==
	// Required: true
	// Format: byte
	CiphertextBlob *strfmt.Base64 `json:"ciphertext_blob"`

	// 加密上下文（必须与加密时一致）
	EncryptionContext map[string]string `json:"encryption_context,omitempty"`
}

// Validate validates this post decrypt payload
func (m *PostDecryptPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCiphertextBlob(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostDecryptPayload) validateCiphertextBlob(formats strfmt.Registry) error {

	if err := validate.Required("ciphertext_blob", "body", m.CiphertextBlob); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post decrypt payload based on context it is used
func (m *PostDecryptPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostDecryptPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDecryptPayload) UnmarshalBinary(b []byte) error {
	var res PostDecryptPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
