// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCreatePolicyPayload post create policy payload
//
// swagger:model postCreatePolicyPayload
type PostCreatePolicyPayload struct {

	// 策略描述
	// Example: 允许创建和使用密钥的策略
	Description string `json:"description,omitempty"`

	// 策略文档（JSON格式）
	// Example: {"statements":[{"actions":["create_key","encrypt","decrypt"],"effect":"Allow","resources":["*"]}]}
	// Required: true
	PolicyDocument interface{} `json:"policy_document"`

	// 策略ID
	// Example: policy-1234567890abcdef
	// Required: true
	PolicyID *string `json:"policy_id"`
}

// Validate validates this post create policy payload
func (m *PostCreatePolicyPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePolicyDocument(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePolicyID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCreatePolicyPayload) validatePolicyDocument(formats strfmt.Registry) error {

	if m.PolicyDocument == nil {
		return errors.Required("policy_document", "body", nil)
	}

	return nil
}

func (m *PostCreatePolicyPayload) validatePolicyID(formats strfmt.Registry) error {

	if err := validate.Required("policy_id", "body", m.PolicyID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post create policy payload based on context it is used
func (m *PostCreatePolicyPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostCreatePolicyPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCreatePolicyPayload) UnmarshalBinary(b []byte) error {
	var res PostCreatePolicyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
