// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCreateSecretPayload post create secret payload
//
// swagger:model postCreateSecretPayload
type PostCreateSecretPayload struct {

	// 要存储的数据（base64编码）
	// Example: eyJ2ZXJzaW9uIjozLCJpZCI6InV1aWQiLCJjcnlwdG8iOnsiY2lwaGVydGV4dCI6ImVuY3J5cHRlZF9tbmVtb25pY19oZXgiLCJjaXBoZXJwYXJhbXMiOnsiaXYiOiJpdl9oZXgifSwiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJrZGYiOiJzY3J5cHQiLCJrZGZwYXJhbXMiOnsiZGtsZW4iOjMyLCJzYWx0Ijoic2FsdF9oZXgiLCJuIjoyNjIxNDQsInIiOjgsInAiOjF9LCJtYWMiOiJtYWNfaGV4In19fQ==
	// Required: true
	// Format: byte
	Data *strfmt.Base64 `json:"data"`

	// Secret 标识符
	// Example: wallet-keystore-00000000-0000-0000-0000-000000000001
	// Required: true
	KeyID *string `json:"key_id"`
}

// Validate validates this post create secret payload
func (m *PostCreateSecretPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCreateSecretPayload) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	return nil
}

func (m *PostCreateSecretPayload) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post create secret payload based on context it is used
func (m *PostCreateSecretPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostCreateSecretPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCreateSecretPayload) UnmarshalBinary(b []byte) error {
	var res PostCreateSecretPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
