// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutUpdateKeyPayload put update key payload
//
// swagger:model putUpdateKeyPayload
type PutUpdateKeyPayload struct {

	// 密钥描述
	Description string `json:"description,omitempty"`

	// 策略ID
	PolicyID string `json:"policy_id,omitempty"`

	// tags
	Tags map[string]string `json:"tags,omitempty"`
}

// Validate validates this put update key payload
func (m *PutUpdateKeyPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put update key payload based on context it is used
func (m *PutUpdateKeyPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PutUpdateKeyPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PutUpdateKeyPayload) UnmarshalBinary(b []byte) error {
	var res PutUpdateKeyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
