// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutUpdatePolicyPayload put update policy payload
//
// swagger:model putUpdatePolicyPayload
type PutUpdatePolicyPayload struct {

	// 策略描述
	Description string `json:"description,omitempty"`

	// 策略文档（JSON格式）
	PolicyDocument interface{} `json:"policy_document,omitempty"`
}

// Validate validates this put update policy payload
func (m *PutUpdatePolicyPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put update policy payload based on context it is used
func (m *PutUpdatePolicyPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PutUpdatePolicyPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PutUpdatePolicyPayload) UnmarshalBinary(b []byte) error {
	var res PutUpdatePolicyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
