// Code generated by go-swagger; DO NOT EDIT.

package kms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteKeyRouteParams creates a new DeleteKeyRouteParams object
// no default values defined in spec.
func NewDeleteKeyRouteParams() DeleteKeyRouteParams {

	return DeleteKeyRouteParams{}
}

// DeleteKeyRouteParams contains all the bound params for the delete key route operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteKeyRoute
type DeleteKeyRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Key ID
	  Required: true
	  In: path
	*/
	KeyID string `param:"keyId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteKeyRouteParams() beforehand.
func (o *DeleteKeyRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rKeyID, rhkKeyID, _ := route.Params.GetOK("keyId")
	if err := o.bindKeyID(rKeyID, rhkKeyID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteKeyRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// keyId
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindKeyID binds and validates parameter KeyID from path.
func (o *DeleteKeyRouteParams) bindKeyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.KeyID = raw

	return nil
}
