// Code generated by go-swagger; DO NOT EDIT.

package kms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeletePolicyRouteParams creates a new DeletePolicyRouteParams object
// no default values defined in spec.
func NewDeletePolicyRouteParams() DeletePolicyRouteParams {

	return DeletePolicyRouteParams{}
}

// DeletePolicyRouteParams contains all the bound params for the delete policy route operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeletePolicyRoute
type DeletePolicyRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Policy ID
	  Required: true
	  In: path
	*/
	PolicyID string `param:"policyId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeletePolicyRouteParams() beforehand.
func (o *DeletePolicyRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rPolicyID, rhkPolicyID, _ := route.Params.GetOK("policyId")
	if err := o.bindPolicyID(rPolicyID, rhkPolicyID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePolicyRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// policyId
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPolicyID binds and validates parameter PolicyID from path.
func (o *DeletePolicyRouteParams) bindPolicyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.PolicyID = raw

	return nil
}
