// Code generated by go-swagger; DO NOT EDIT.

package kms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetListKeysRouteParams creates a new GetListKeysRouteParams object
// with the default values initialized.
func NewGetListKeysRouteParams() GetListKeysRouteParams {

	var (
		// initialize parameters with default values

		limitDefault  = int64(100)
		offsetDefault = int64(0)
	)

	return GetListKeysRouteParams{
		Limit: &limitDefault,

		Offset: &offsetDefault,
	}
}

// GetListKeysRouteParams contains all the bound params for the get list keys route operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetListKeysRoute
type GetListKeysRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Filter by alias (prefix match)
	  In: query
	*/
	Alias *string `query:"alias"`
	/*Filter by key type
	  In: query
	*/
	KeyType *string `query:"key_type"`
	/*Maximum number of results
	  In: query
	  Default: 100
	*/
	Limit *int64 `query:"limit"`
	/*Offset for pagination
	  In: query
	  Default: 0
	*/
	Offset *int64 `query:"offset"`
	/*Filter by key state
	  In: query
	*/
	State *string `query:"state"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetListKeysRouteParams() beforehand.
func (o *GetListKeysRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAlias, qhkAlias, _ := qs.GetOK("alias")
	if err := o.bindAlias(qAlias, qhkAlias, route.Formats); err != nil {
		res = append(res, err)
	}

	qKeyType, qhkKeyType, _ := qs.GetOK("key_type")
	if err := o.bindKeyType(qKeyType, qhkKeyType, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qOffset, qhkOffset, _ := qs.GetOK("offset")
	if err := o.bindOffset(qOffset, qhkOffset, route.Formats); err != nil {
		res = append(res, err)
	}

	qState, qhkState, _ := qs.GetOK("state")
	if err := o.bindState(qState, qhkState, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetListKeysRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// alias
	// Required: false
	// AllowEmptyValue: false

	// key_type
	// Required: false
	// AllowEmptyValue: false

	// limit
	// Required: false
	// AllowEmptyValue: false

	// offset
	// Required: false
	// AllowEmptyValue: false

	// state
	// Required: false
	// AllowEmptyValue: false

	if err := o.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAlias binds and validates parameter Alias from query.
func (o *GetListKeysRouteParams) bindAlias(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Alias = &raw

	return nil
}

// bindKeyType binds and validates parameter KeyType from query.
func (o *GetListKeysRouteParams) bindKeyType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.KeyType = &raw

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetListKeysRouteParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetListKeysRouteParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int64", raw)
	}
	o.Limit = &value

	return nil
}

// bindOffset binds and validates parameter Offset from query.
func (o *GetListKeysRouteParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetListKeysRouteParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("offset", "query", "int64", raw)
	}
	o.Offset = &value

	return nil
}

// bindState binds and validates parameter State from query.
func (o *GetListKeysRouteParams) bindState(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.State = &raw

	if err := o.validateState(formats); err != nil {
		return err
	}

	return nil
}

// validateState carries on validations for parameter State
func (o *GetListKeysRouteParams) validateState(formats strfmt.Registry) error {

	// Required: false
	if o.State == nil {
		return nil
	}

	if err := validate.EnumCase("state", "query", *o.State, []interface{}{"Enabled", "Disabled", "PendingDeletion"}, true); err != nil {
		return err
	}

	return nil
}
