// Code generated by go-swagger; DO NOT EDIT.

package kms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetListPoliciesRouteParams creates a new GetListPoliciesRouteParams object
// no default values defined in spec.
func NewGetListPoliciesRouteParams() GetListPoliciesRouteParams {

	return GetListPoliciesRouteParams{}
}

// GetListPoliciesRouteParams contains all the bound params for the get list policies route operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetListPoliciesRoute
type GetListPoliciesRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetListPoliciesRouteParams() beforehand.
func (o *GetListPoliciesRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetListPoliciesRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
