// Code generated by go-swagger; DO NOT EDIT.

package kms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetAuditLogsRouteParams creates a new GetAuditLogsRouteParams object
// with the default values initialized.
func NewGetAuditLogsRouteParams() GetAuditLogsRouteParams {

	var (
		// initialize parameters with default values

		limitDefault  = int64(100)
		offsetDefault = int64(0)
	)

	return GetAuditLogsRouteParams{
		Limit: &limitDefault,

		Offset: &offsetDefault,
	}
}

// GetAuditLogsRouteParams contains all the bound params for the get audit logs route operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetAuditLogsRoute
type GetAuditLogsRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*End time
	  In: query
	*/
	EndTime *strfmt.DateTime `query:"end_time"`
	/*Filter by event type
	  In: query
	*/
	EventType *string `query:"event_type"`
	/*Filter by key ID
	  In: query
	*/
	KeyID *string `query:"key_id"`
	/*Maximum number of results
	  In: query
	  Default: 100
	*/
	Limit *int64 `query:"limit"`
	/*Offset for pagination
	  In: query
	  Default: 0
	*/
	Offset *int64 `query:"offset"`
	/*Filter by operation
	  In: query
	*/
	Operation *string `query:"operation"`
	/*Filter by result
	  In: query
	*/
	Result *string `query:"result"`
	/*Start time
	  In: query
	*/
	StartTime *strfmt.DateTime `query:"start_time"`
	/*Filter by user ID
	  In: query
	*/
	UserID *string `query:"user_id"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAuditLogsRouteParams() beforehand.
func (o *GetAuditLogsRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qEndTime, qhkEndTime, _ := qs.GetOK("end_time")
	if err := o.bindEndTime(qEndTime, qhkEndTime, route.Formats); err != nil {
		res = append(res, err)
	}

	qEventType, qhkEventType, _ := qs.GetOK("event_type")
	if err := o.bindEventType(qEventType, qhkEventType, route.Formats); err != nil {
		res = append(res, err)
	}

	qKeyID, qhkKeyID, _ := qs.GetOK("key_id")
	if err := o.bindKeyID(qKeyID, qhkKeyID, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qOffset, qhkOffset, _ := qs.GetOK("offset")
	if err := o.bindOffset(qOffset, qhkOffset, route.Formats); err != nil {
		res = append(res, err)
	}

	qOperation, qhkOperation, _ := qs.GetOK("operation")
	if err := o.bindOperation(qOperation, qhkOperation, route.Formats); err != nil {
		res = append(res, err)
	}

	qResult, qhkResult, _ := qs.GetOK("result")
	if err := o.bindResult(qResult, qhkResult, route.Formats); err != nil {
		res = append(res, err)
	}

	qStartTime, qhkStartTime, _ := qs.GetOK("start_time")
	if err := o.bindStartTime(qStartTime, qhkStartTime, route.Formats); err != nil {
		res = append(res, err)
	}

	qUserID, qhkUserID, _ := qs.GetOK("user_id")
	if err := o.bindUserID(qUserID, qhkUserID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAuditLogsRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// end_time
	// Required: false
	// AllowEmptyValue: false

	if err := o.validateEndTime(formats); err != nil {
		res = append(res, err)
	}

	// event_type
	// Required: false
	// AllowEmptyValue: false

	// key_id
	// Required: false
	// AllowEmptyValue: false

	// limit
	// Required: false
	// AllowEmptyValue: false

	// offset
	// Required: false
	// AllowEmptyValue: false

	// operation
	// Required: false
	// AllowEmptyValue: false

	// result
	// Required: false
	// AllowEmptyValue: false

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	// start_time
	// Required: false
	// AllowEmptyValue: false

	if err := o.validateStartTime(formats); err != nil {
		res = append(res, err)
	}

	// user_id
	// Required: false
	// AllowEmptyValue: false

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEndTime binds and validates parameter EndTime from query.
func (o *GetAuditLogsRouteParams) bindEndTime(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: date-time
	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("end_time", "query", "strfmt.DateTime", raw)
	}
	o.EndTime = (value.(*strfmt.DateTime))

	if err := o.validateEndTime(formats); err != nil {
		return err
	}

	return nil
}

// validateEndTime carries on validations for parameter EndTime
func (o *GetAuditLogsRouteParams) validateEndTime(formats strfmt.Registry) error {

	// Required: false
	if o.EndTime == nil {
		return nil
	}

	if err := validate.FormatOf("end_time", "query", "date-time", (*o.EndTime).String(), formats); err != nil {
		return err
	}
	return nil
}

// bindEventType binds and validates parameter EventType from query.
func (o *GetAuditLogsRouteParams) bindEventType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.EventType = &raw

	return nil
}

// bindKeyID binds and validates parameter KeyID from query.
func (o *GetAuditLogsRouteParams) bindKeyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.KeyID = &raw

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetAuditLogsRouteParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetAuditLogsRouteParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int64", raw)
	}
	o.Limit = &value

	return nil
}

// bindOffset binds and validates parameter Offset from query.
func (o *GetAuditLogsRouteParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetAuditLogsRouteParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("offset", "query", "int64", raw)
	}
	o.Offset = &value

	return nil
}

// bindOperation binds and validates parameter Operation from query.
func (o *GetAuditLogsRouteParams) bindOperation(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Operation = &raw

	return nil
}

// bindResult binds and validates parameter Result from query.
func (o *GetAuditLogsRouteParams) bindResult(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Result = &raw

	if err := o.validateResult(formats); err != nil {
		return err
	}

	return nil
}

// validateResult carries on validations for parameter Result
func (o *GetAuditLogsRouteParams) validateResult(formats strfmt.Registry) error {

	// Required: false
	if o.Result == nil {
		return nil
	}

	if err := validate.EnumCase("result", "query", *o.Result, []interface{}{"Success", "Failed"}, true); err != nil {
		return err
	}

	return nil
}

// bindStartTime binds and validates parameter StartTime from query.
func (o *GetAuditLogsRouteParams) bindStartTime(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: date-time
	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("start_time", "query", "strfmt.DateTime", raw)
	}
	o.StartTime = (value.(*strfmt.DateTime))

	if err := o.validateStartTime(formats); err != nil {
		return err
	}

	return nil
}

// validateStartTime carries on validations for parameter StartTime
func (o *GetAuditLogsRouteParams) validateStartTime(formats strfmt.Registry) error {

	// Required: false
	if o.StartTime == nil {
		return nil
	}

	if err := validate.FormatOf("start_time", "query", "date-time", (*o.StartTime).String(), formats); err != nil {
		return err
	}
	return nil
}

// bindUserID binds and validates parameter UserID from query.
func (o *GetAuditLogsRouteParams) bindUserID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.UserID = &raw

	return nil
}
