// Code generated by go-swagger; DO NOT EDIT.

package kms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/kashguard/go-kms/internal/types"
)

// NewPutUpdateKeyRouteParams creates a new PutUpdateKeyRouteParams object
// no default values defined in spec.
func NewPutUpdateKeyRouteParams() PutUpdateKeyRouteParams {

	return PutUpdateKeyRouteParams{}
}

// PutUpdateKeyRouteParams contains all the bound params for the put update key route operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutUpdateKeyRoute
type PutUpdateKeyRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Payload *types.PutUpdateKeyPayload
	/*Key ID
	  Required: true
	  In: path
	*/
	KeyID string `param:"keyId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutUpdateKeyRouteParams() beforehand.
func (o *PutUpdateKeyRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body types.PutUpdateKeyPayload
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("payload", "body", ""))
			} else {
				res = append(res, errors.NewParseError("payload", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Payload = &body
			}
		}
	} else {
		res = append(res, errors.Required("payload", "body", ""))
	}
	rKeyID, rhkKeyID, _ := route.Params.GetOK("keyId")
	if err := o.bindKeyID(rKeyID, rhkKeyID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutUpdateKeyRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// Payload
	// Required: true

	// body is validated in endpoint
	//if err := o.Payload.Validate(formats); err != nil {
	//  res = append(res, err)
	//}

	// keyId
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindKeyID binds and validates parameter KeyID from path.
func (o *PutUpdateKeyRouteParams) bindKeyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.KeyID = raw

	return nil
}
