// Code generated by go-swagger; DO NOT EDIT.

package kms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/kashguard/go-kms/internal/types"
)

// NewPutUpdatePolicyRouteParams creates a new PutUpdatePolicyRouteParams object
// no default values defined in spec.
func NewPutUpdatePolicyRouteParams() PutUpdatePolicyRouteParams {

	return PutUpdatePolicyRouteParams{}
}

// PutUpdatePolicyRouteParams contains all the bound params for the put update policy route operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutUpdatePolicyRoute
type PutUpdatePolicyRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Payload *types.PutUpdatePolicyPayload
	/*Policy ID
	  Required: true
	  In: path
	*/
	PolicyID string `param:"policyId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutUpdatePolicyRouteParams() beforehand.
func (o *PutUpdatePolicyRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body types.PutUpdatePolicyPayload
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("payload", "body", ""))
			} else {
				res = append(res, errors.NewParseError("payload", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Payload = &body
			}
		}
	} else {
		res = append(res, errors.Required("payload", "body", ""))
	}
	rPolicyID, rhkPolicyID, _ := route.Params.GetOK("policyId")
	if err := o.bindPolicyID(rPolicyID, rhkPolicyID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutUpdatePolicyRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// Payload
	// Required: true

	// body is validated in endpoint
	//if err := o.Payload.Validate(formats); err != nil {
	//  res = append(res, err)
	//}

	// policyId
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPolicyID binds and validates parameter PolicyID from path.
func (o *PutUpdatePolicyRouteParams) bindPolicyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.PolicyID = raw

	return nil
}
