// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("AccessTokens", testAccessTokens)
	t.Run("AppUserProfiles", testAppUserProfiles)
	t.Run("AuditLogs", testAuditLogs)
	t.Run("ConfirmationTokens", testConfirmationTokens)
	t.Run("KeyVersions", testKeyVersions)
	t.Run("Keys", testKeys)
	t.Run("PasswordResetTokens", testPasswordResetTokens)
	t.Run("Policies", testPolicies)
	t.Run("PushTokens", testPushTokens)
	t.Run("RefreshTokens", testRefreshTokens)
	t.Run("Secrets", testSecrets)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensDelete)
	t.Run("AppUserProfiles", testAppUserProfilesDelete)
	t.Run("AuditLogs", testAuditLogsDelete)
	t.Run("ConfirmationTokens", testConfirmationTokensDelete)
	t.Run("KeyVersions", testKeyVersionsDelete)
	t.Run("Keys", testKeysDelete)
	t.Run("PasswordResetTokens", testPasswordResetTokensDelete)
	t.Run("Policies", testPoliciesDelete)
	t.Run("PushTokens", testPushTokensDelete)
	t.Run("RefreshTokens", testRefreshTokensDelete)
	t.Run("Secrets", testSecretsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensQueryDeleteAll)
	t.Run("AppUserProfiles", testAppUserProfilesQueryDeleteAll)
	t.Run("AuditLogs", testAuditLogsQueryDeleteAll)
	t.Run("ConfirmationTokens", testConfirmationTokensQueryDeleteAll)
	t.Run("KeyVersions", testKeyVersionsQueryDeleteAll)
	t.Run("Keys", testKeysQueryDeleteAll)
	t.Run("PasswordResetTokens", testPasswordResetTokensQueryDeleteAll)
	t.Run("Policies", testPoliciesQueryDeleteAll)
	t.Run("PushTokens", testPushTokensQueryDeleteAll)
	t.Run("RefreshTokens", testRefreshTokensQueryDeleteAll)
	t.Run("Secrets", testSecretsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensSliceDeleteAll)
	t.Run("AppUserProfiles", testAppUserProfilesSliceDeleteAll)
	t.Run("AuditLogs", testAuditLogsSliceDeleteAll)
	t.Run("ConfirmationTokens", testConfirmationTokensSliceDeleteAll)
	t.Run("KeyVersions", testKeyVersionsSliceDeleteAll)
	t.Run("Keys", testKeysSliceDeleteAll)
	t.Run("PasswordResetTokens", testPasswordResetTokensSliceDeleteAll)
	t.Run("Policies", testPoliciesSliceDeleteAll)
	t.Run("PushTokens", testPushTokensSliceDeleteAll)
	t.Run("RefreshTokens", testRefreshTokensSliceDeleteAll)
	t.Run("Secrets", testSecretsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensExists)
	t.Run("AppUserProfiles", testAppUserProfilesExists)
	t.Run("AuditLogs", testAuditLogsExists)
	t.Run("ConfirmationTokens", testConfirmationTokensExists)
	t.Run("KeyVersions", testKeyVersionsExists)
	t.Run("Keys", testKeysExists)
	t.Run("PasswordResetTokens", testPasswordResetTokensExists)
	t.Run("Policies", testPoliciesExists)
	t.Run("PushTokens", testPushTokensExists)
	t.Run("RefreshTokens", testRefreshTokensExists)
	t.Run("Secrets", testSecretsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensFind)
	t.Run("AppUserProfiles", testAppUserProfilesFind)
	t.Run("AuditLogs", testAuditLogsFind)
	t.Run("ConfirmationTokens", testConfirmationTokensFind)
	t.Run("KeyVersions", testKeyVersionsFind)
	t.Run("Keys", testKeysFind)
	t.Run("PasswordResetTokens", testPasswordResetTokensFind)
	t.Run("Policies", testPoliciesFind)
	t.Run("PushTokens", testPushTokensFind)
	t.Run("RefreshTokens", testRefreshTokensFind)
	t.Run("Secrets", testSecretsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensBind)
	t.Run("AppUserProfiles", testAppUserProfilesBind)
	t.Run("AuditLogs", testAuditLogsBind)
	t.Run("ConfirmationTokens", testConfirmationTokensBind)
	t.Run("KeyVersions", testKeyVersionsBind)
	t.Run("Keys", testKeysBind)
	t.Run("PasswordResetTokens", testPasswordResetTokensBind)
	t.Run("Policies", testPoliciesBind)
	t.Run("PushTokens", testPushTokensBind)
	t.Run("RefreshTokens", testRefreshTokensBind)
	t.Run("Secrets", testSecretsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensOne)
	t.Run("AppUserProfiles", testAppUserProfilesOne)
	t.Run("AuditLogs", testAuditLogsOne)
	t.Run("ConfirmationTokens", testConfirmationTokensOne)
	t.Run("KeyVersions", testKeyVersionsOne)
	t.Run("Keys", testKeysOne)
	t.Run("PasswordResetTokens", testPasswordResetTokensOne)
	t.Run("Policies", testPoliciesOne)
	t.Run("PushTokens", testPushTokensOne)
	t.Run("RefreshTokens", testRefreshTokensOne)
	t.Run("Secrets", testSecretsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensAll)
	t.Run("AppUserProfiles", testAppUserProfilesAll)
	t.Run("AuditLogs", testAuditLogsAll)
	t.Run("ConfirmationTokens", testConfirmationTokensAll)
	t.Run("KeyVersions", testKeyVersionsAll)
	t.Run("Keys", testKeysAll)
	t.Run("PasswordResetTokens", testPasswordResetTokensAll)
	t.Run("Policies", testPoliciesAll)
	t.Run("PushTokens", testPushTokensAll)
	t.Run("RefreshTokens", testRefreshTokensAll)
	t.Run("Secrets", testSecretsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensCount)
	t.Run("AppUserProfiles", testAppUserProfilesCount)
	t.Run("AuditLogs", testAuditLogsCount)
	t.Run("ConfirmationTokens", testConfirmationTokensCount)
	t.Run("KeyVersions", testKeyVersionsCount)
	t.Run("Keys", testKeysCount)
	t.Run("PasswordResetTokens", testPasswordResetTokensCount)
	t.Run("Policies", testPoliciesCount)
	t.Run("PushTokens", testPushTokensCount)
	t.Run("RefreshTokens", testRefreshTokensCount)
	t.Run("Secrets", testSecretsCount)
	t.Run("Users", testUsersCount)
}

func TestInsert(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensInsert)
	t.Run("AccessTokens", testAccessTokensInsertWhitelist)
	t.Run("AppUserProfiles", testAppUserProfilesInsert)
	t.Run("AppUserProfiles", testAppUserProfilesInsertWhitelist)
	t.Run("AuditLogs", testAuditLogsInsert)
	t.Run("AuditLogs", testAuditLogsInsertWhitelist)
	t.Run("ConfirmationTokens", testConfirmationTokensInsert)
	t.Run("ConfirmationTokens", testConfirmationTokensInsertWhitelist)
	t.Run("KeyVersions", testKeyVersionsInsert)
	t.Run("KeyVersions", testKeyVersionsInsertWhitelist)
	t.Run("Keys", testKeysInsert)
	t.Run("Keys", testKeysInsertWhitelist)
	t.Run("PasswordResetTokens", testPasswordResetTokensInsert)
	t.Run("PasswordResetTokens", testPasswordResetTokensInsertWhitelist)
	t.Run("Policies", testPoliciesInsert)
	t.Run("Policies", testPoliciesInsertWhitelist)
	t.Run("PushTokens", testPushTokensInsert)
	t.Run("PushTokens", testPushTokensInsertWhitelist)
	t.Run("RefreshTokens", testRefreshTokensInsert)
	t.Run("RefreshTokens", testRefreshTokensInsertWhitelist)
	t.Run("Secrets", testSecretsInsert)
	t.Run("Secrets", testSecretsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensReload)
	t.Run("AppUserProfiles", testAppUserProfilesReload)
	t.Run("AuditLogs", testAuditLogsReload)
	t.Run("ConfirmationTokens", testConfirmationTokensReload)
	t.Run("KeyVersions", testKeyVersionsReload)
	t.Run("Keys", testKeysReload)
	t.Run("PasswordResetTokens", testPasswordResetTokensReload)
	t.Run("Policies", testPoliciesReload)
	t.Run("PushTokens", testPushTokensReload)
	t.Run("RefreshTokens", testRefreshTokensReload)
	t.Run("Secrets", testSecretsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensReloadAll)
	t.Run("AppUserProfiles", testAppUserProfilesReloadAll)
	t.Run("AuditLogs", testAuditLogsReloadAll)
	t.Run("ConfirmationTokens", testConfirmationTokensReloadAll)
	t.Run("KeyVersions", testKeyVersionsReloadAll)
	t.Run("Keys", testKeysReloadAll)
	t.Run("PasswordResetTokens", testPasswordResetTokensReloadAll)
	t.Run("Policies", testPoliciesReloadAll)
	t.Run("PushTokens", testPushTokensReloadAll)
	t.Run("RefreshTokens", testRefreshTokensReloadAll)
	t.Run("Secrets", testSecretsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensSelect)
	t.Run("AppUserProfiles", testAppUserProfilesSelect)
	t.Run("AuditLogs", testAuditLogsSelect)
	t.Run("ConfirmationTokens", testConfirmationTokensSelect)
	t.Run("KeyVersions", testKeyVersionsSelect)
	t.Run("Keys", testKeysSelect)
	t.Run("PasswordResetTokens", testPasswordResetTokensSelect)
	t.Run("Policies", testPoliciesSelect)
	t.Run("PushTokens", testPushTokensSelect)
	t.Run("RefreshTokens", testRefreshTokensSelect)
	t.Run("Secrets", testSecretsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensUpdate)
	t.Run("AppUserProfiles", testAppUserProfilesUpdate)
	t.Run("AuditLogs", testAuditLogsUpdate)
	t.Run("ConfirmationTokens", testConfirmationTokensUpdate)
	t.Run("KeyVersions", testKeyVersionsUpdate)
	t.Run("Keys", testKeysUpdate)
	t.Run("PasswordResetTokens", testPasswordResetTokensUpdate)
	t.Run("Policies", testPoliciesUpdate)
	t.Run("PushTokens", testPushTokensUpdate)
	t.Run("RefreshTokens", testRefreshTokensUpdate)
	t.Run("Secrets", testSecretsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensSliceUpdateAll)
	t.Run("AppUserProfiles", testAppUserProfilesSliceUpdateAll)
	t.Run("AuditLogs", testAuditLogsSliceUpdateAll)
	t.Run("ConfirmationTokens", testConfirmationTokensSliceUpdateAll)
	t.Run("KeyVersions", testKeyVersionsSliceUpdateAll)
	t.Run("Keys", testKeysSliceUpdateAll)
	t.Run("PasswordResetTokens", testPasswordResetTokensSliceUpdateAll)
	t.Run("Policies", testPoliciesSliceUpdateAll)
	t.Run("PushTokens", testPushTokensSliceUpdateAll)
	t.Run("RefreshTokens", testRefreshTokensSliceUpdateAll)
	t.Run("Secrets", testSecretsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
