// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccessTokens        string
	AppUserProfiles     string
	AuditLogs           string
	ConfirmationTokens  string
	KeyVersions         string
	Keys                string
	PasswordResetTokens string
	Policies            string
	PushTokens          string
	RefreshTokens       string
	Secrets             string
	Users               string
}{
	AccessTokens:        "access_tokens",
	AppUserProfiles:     "app_user_profiles",
	AuditLogs:           "audit_logs",
	ConfirmationTokens:  "confirmation_tokens",
	KeyVersions:         "key_versions",
	Keys:                "keys",
	PasswordResetTokens: "password_reset_tokens",
	Policies:            "policies",
	PushTokens:          "push_tokens",
	RefreshTokens:       "refresh_tokens",
	Secrets:             "secrets",
	Users:               "users",
}
