// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testKeyVersions(t *testing.T) {
	t.Parallel()

	query := KeyVersions()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testKeyVersionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := KeyVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeyVersionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := KeyVersions().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := KeyVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeyVersionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := KeyVersionSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := KeyVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeyVersionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := KeyVersionExists(ctx, tx, o.KeyID, o.Version)
	if err != nil {
		t.Errorf("Unable to check if KeyVersion exists: %s", err)
	}
	if !e {
		t.Errorf("Expected KeyVersionExists to return true, but got false.")
	}
}

func testKeyVersionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	keyVersionFound, err := FindKeyVersion(ctx, tx, o.KeyID, o.Version)
	if err != nil {
		t.Error(err)
	}

	if keyVersionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testKeyVersionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = KeyVersions().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testKeyVersionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := KeyVersions().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testKeyVersionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	keyVersionOne := &KeyVersion{}
	keyVersionTwo := &KeyVersion{}
	if err = randomize.Struct(seed, keyVersionOne, keyVersionDBTypes, false, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}
	if err = randomize.Struct(seed, keyVersionTwo, keyVersionDBTypes, false, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = keyVersionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = keyVersionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := KeyVersions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testKeyVersionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	keyVersionOne := &KeyVersion{}
	keyVersionTwo := &KeyVersion{}
	if err = randomize.Struct(seed, keyVersionOne, keyVersionDBTypes, false, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}
	if err = randomize.Struct(seed, keyVersionTwo, keyVersionDBTypes, false, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = keyVersionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = keyVersionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := KeyVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testKeyVersionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := KeyVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testKeyVersionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(keyVersionPrimaryKeyColumns, keyVersionColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := KeyVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testKeyVersionToOneKeyUsingKey(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local KeyVersion
	var foreign Key

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, keyVersionDBTypes, false, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, keyDBTypes, false, keyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Key struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.KeyID = foreign.KeyID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Key().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.KeyID != foreign.KeyID {
		t.Errorf("want: %v, got %v", foreign.KeyID, check.KeyID)
	}

	slice := KeyVersionSlice{&local}
	if err = local.L.LoadKey(ctx, tx, false, (*[]*KeyVersion)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Key == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Key = nil
	if err = local.L.LoadKey(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Key == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testKeyVersionToOneSetOpKeyUsingKey(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a KeyVersion
	var b, c Key

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, keyVersionDBTypes, false, strmangle.SetComplement(keyVersionPrimaryKeyColumns, keyVersionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, keyDBTypes, false, strmangle.SetComplement(keyPrimaryKeyColumns, keyColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, keyDBTypes, false, strmangle.SetComplement(keyPrimaryKeyColumns, keyColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Key{&b, &c} {
		err = a.SetKey(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Key != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.KeyVersions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.KeyID != x.KeyID {
			t.Error("foreign key was wrong value", a.KeyID)
		}

		if exists, err := KeyVersionExists(ctx, tx, a.KeyID, a.Version); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}

func testKeyVersionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testKeyVersionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := KeyVersionSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testKeyVersionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := KeyVersions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	keyVersionDBTypes = map[string]string{`KeyID`: `character varying`, `Version`: `integer`, `HSMHandle`: `character varying`, `IsPrimary`: `boolean`, `CreatedAt`: `timestamp with time zone`}
	_                 = bytes.MinRead
)

func testKeyVersionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(keyVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(keyVersionAllColumns) == len(keyVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := KeyVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testKeyVersionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(keyVersionAllColumns) == len(keyVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &KeyVersion{}
	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := KeyVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, keyVersionDBTypes, true, keyVersionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(keyVersionAllColumns, keyVersionPrimaryKeyColumns) {
		fields = keyVersionAllColumns
	} else {
		fields = strmangle.SetComplement(
			keyVersionAllColumns,
			keyVersionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := KeyVersionSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testKeyVersionsUpsert(t *testing.T) {
	t.Parallel()

	if len(keyVersionAllColumns) == len(keyVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := KeyVersion{}
	if err = randomize.Struct(seed, &o, keyVersionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert KeyVersion: %s", err)
	}

	count, err := KeyVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, keyVersionDBTypes, false, keyVersionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize KeyVersion struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert KeyVersion: %s", err)
	}

	count, err = KeyVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
