// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Key is an object representing the database table.
type Key struct {
	KeyID        string      `boil:"key_id" json:"key_id" toml:"key_id" yaml:"key_id"`
	Alias        null.String `boil:"alias" json:"alias,omitempty" toml:"alias" yaml:"alias,omitempty"`
	Description  null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	KeyType      string      `boil:"key_type" json:"key_type" toml:"key_type" yaml:"key_type"`
	KeyState     string      `boil:"key_state" json:"key_state" toml:"key_state" yaml:"key_state"`
	KeySpec      null.JSON   `boil:"key_spec" json:"key_spec,omitempty" toml:"key_spec" yaml:"key_spec,omitempty"`
	HSMHandle    string      `boil:"hsm_handle" json:"hsm_handle" toml:"hsm_handle" yaml:"hsm_handle"`
	PolicyID     null.String `boil:"policy_id" json:"policy_id,omitempty" toml:"policy_id" yaml:"policy_id,omitempty"`
	CreatedAt    time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletionDate null.Time   `boil:"deletion_date" json:"deletion_date,omitempty" toml:"deletion_date" yaml:"deletion_date,omitempty"`
	Tags         null.JSON   `boil:"tags" json:"tags,omitempty" toml:"tags" yaml:"tags,omitempty"`

	R *keyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L keyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var KeyColumns = struct {
	KeyID        string
	Alias        string
	Description  string
	KeyType      string
	KeyState     string
	KeySpec      string
	HSMHandle    string
	PolicyID     string
	CreatedAt    string
	UpdatedAt    string
	DeletionDate string
	Tags         string
}{
	KeyID:        "key_id",
	Alias:        "alias",
	Description:  "description",
	KeyType:      "key_type",
	KeyState:     "key_state",
	KeySpec:      "key_spec",
	HSMHandle:    "hsm_handle",
	PolicyID:     "policy_id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletionDate: "deletion_date",
	Tags:         "tags",
}

var KeyTableColumns = struct {
	KeyID        string
	Alias        string
	Description  string
	KeyType      string
	KeyState     string
	KeySpec      string
	HSMHandle    string
	PolicyID     string
	CreatedAt    string
	UpdatedAt    string
	DeletionDate string
	Tags         string
}{
	KeyID:        "keys.key_id",
	Alias:        "keys.alias",
	Description:  "keys.description",
	KeyType:      "keys.key_type",
	KeyState:     "keys.key_state",
	KeySpec:      "keys.key_spec",
	HSMHandle:    "keys.hsm_handle",
	PolicyID:     "keys.policy_id",
	CreatedAt:    "keys.created_at",
	UpdatedAt:    "keys.updated_at",
	DeletionDate: "keys.deletion_date",
	Tags:         "keys.tags",
}

// Generated where

var KeyWhere = struct {
	KeyID        whereHelperstring
	Alias        whereHelpernull_String
	Description  whereHelpernull_String
	KeyType      whereHelperstring
	KeyState     whereHelperstring
	KeySpec      whereHelpernull_JSON
	HSMHandle    whereHelperstring
	PolicyID     whereHelpernull_String
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
	DeletionDate whereHelpernull_Time
	Tags         whereHelpernull_JSON
}{
	KeyID:        whereHelperstring{field: "\"keys\".\"key_id\""},
	Alias:        whereHelpernull_String{field: "\"keys\".\"alias\""},
	Description:  whereHelpernull_String{field: "\"keys\".\"description\""},
	KeyType:      whereHelperstring{field: "\"keys\".\"key_type\""},
	KeyState:     whereHelperstring{field: "\"keys\".\"key_state\""},
	KeySpec:      whereHelpernull_JSON{field: "\"keys\".\"key_spec\""},
	HSMHandle:    whereHelperstring{field: "\"keys\".\"hsm_handle\""},
	PolicyID:     whereHelpernull_String{field: "\"keys\".\"policy_id\""},
	CreatedAt:    whereHelpertime_Time{field: "\"keys\".\"created_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"keys\".\"updated_at\""},
	DeletionDate: whereHelpernull_Time{field: "\"keys\".\"deletion_date\""},
	Tags:         whereHelpernull_JSON{field: "\"keys\".\"tags\""},
}

// KeyRels is where relationship names are stored.
var KeyRels = struct {
	KeyVersions   string
	KMSKeySecrets string
}{
	KeyVersions:   "KeyVersions",
	KMSKeySecrets: "KMSKeySecrets",
}

// keyR is where relationships are stored.
type keyR struct {
	KeyVersions   KeyVersionSlice `boil:"KeyVersions" json:"KeyVersions" toml:"KeyVersions" yaml:"KeyVersions"`
	KMSKeySecrets SecretSlice     `boil:"KMSKeySecrets" json:"KMSKeySecrets" toml:"KMSKeySecrets" yaml:"KMSKeySecrets"`
}

// NewStruct creates a new relationship struct
func (*keyR) NewStruct() *keyR {
	return &keyR{}
}

func (o *Key) GetKeyVersions() KeyVersionSlice {
	if o == nil {
		return nil
	}

	return o.R.GetKeyVersions()
}

func (r *keyR) GetKeyVersions() KeyVersionSlice {
	if r == nil {
		return nil
	}

	return r.KeyVersions
}

func (o *Key) GetKMSKeySecrets() SecretSlice {
	if o == nil {
		return nil
	}

	return o.R.GetKMSKeySecrets()
}

func (r *keyR) GetKMSKeySecrets() SecretSlice {
	if r == nil {
		return nil
	}

	return r.KMSKeySecrets
}

// keyL is where Load methods for each relationship are stored.
type keyL struct{}

var (
	keyAllColumns            = []string{"key_id", "alias", "description", "key_type", "key_state", "key_spec", "hsm_handle", "policy_id", "created_at", "updated_at", "deletion_date", "tags"}
	keyColumnsWithoutDefault = []string{"key_id", "key_type", "key_state", "hsm_handle"}
	keyColumnsWithDefault    = []string{"alias", "description", "key_spec", "policy_id", "created_at", "updated_at", "deletion_date", "tags"}
	keyPrimaryKeyColumns     = []string{"key_id"}
	keyGeneratedColumns      = []string{}
)

type (
	// KeySlice is an alias for a slice of pointers to Key.
	// This should almost always be used instead of []Key.
	KeySlice []*Key

	keyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	keyType                 = reflect.TypeOf(&Key{})
	keyMapping              = queries.MakeStructMapping(keyType)
	keyPrimaryKeyMapping, _ = queries.BindMapping(keyType, keyMapping, keyPrimaryKeyColumns)
	keyInsertCacheMut       sync.RWMutex
	keyInsertCache          = make(map[string]insertCache)
	keyUpdateCacheMut       sync.RWMutex
	keyUpdateCache          = make(map[string]updateCache)
	keyUpsertCacheMut       sync.RWMutex
	keyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single key record from the query.
func (q keyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Key, error) {
	o := &Key{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for keys")
	}

	return o, nil
}

// All returns all Key records from the query.
func (q keyQuery) All(ctx context.Context, exec boil.ContextExecutor) (KeySlice, error) {
	var o []*Key

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Key slice")
	}

	return o, nil
}

// Count returns the count of all Key records in the query.
func (q keyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count keys rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q keyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if keys exists")
	}

	return count > 0, nil
}

// KeyVersions retrieves all the key_version's KeyVersions with an executor.
func (o *Key) KeyVersions(mods ...qm.QueryMod) keyVersionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"key_versions\".\"key_id\"=?", o.KeyID),
	)

	return KeyVersions(queryMods...)
}

// KMSKeySecrets retrieves all the secret's Secrets with an executor via kms_key_id column.
func (o *Key) KMSKeySecrets(mods ...qm.QueryMod) secretQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"secrets\".\"kms_key_id\"=?", o.KeyID),
	)

	return Secrets(queryMods...)
}

// LoadKeyVersions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (keyL) LoadKeyVersions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKey interface{}, mods queries.Applicator) error {
	var slice []*Key
	var object *Key

	if singular {
		var ok bool
		object, ok = maybeKey.(*Key)
		if !ok {
			object = new(Key)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeKey))
			}
		}
	} else {
		s, ok := maybeKey.(*[]*Key)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeKey))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &keyR{}
		}
		args[object.KeyID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &keyR{}
			}
			args[obj.KeyID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`key_versions`),
		qm.WhereIn(`key_versions.key_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load key_versions")
	}

	var resultSlice []*KeyVersion
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice key_versions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on key_versions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for key_versions")
	}

	if singular {
		object.R.KeyVersions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &keyVersionR{}
			}
			foreign.R.Key = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.KeyID == foreign.KeyID {
				local.R.KeyVersions = append(local.R.KeyVersions, foreign)
				if foreign.R == nil {
					foreign.R = &keyVersionR{}
				}
				foreign.R.Key = local
				break
			}
		}
	}

	return nil
}

// LoadKMSKeySecrets allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (keyL) LoadKMSKeySecrets(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKey interface{}, mods queries.Applicator) error {
	var slice []*Key
	var object *Key

	if singular {
		var ok bool
		object, ok = maybeKey.(*Key)
		if !ok {
			object = new(Key)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeKey))
			}
		}
	} else {
		s, ok := maybeKey.(*[]*Key)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeKey))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &keyR{}
		}
		args[object.KeyID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &keyR{}
			}
			args[obj.KeyID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`secrets`),
		qm.WhereIn(`secrets.kms_key_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load secrets")
	}

	var resultSlice []*Secret
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice secrets")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on secrets")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for secrets")
	}

	if singular {
		object.R.KMSKeySecrets = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &secretR{}
			}
			foreign.R.KMSKey = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.KeyID == foreign.KMSKeyID {
				local.R.KMSKeySecrets = append(local.R.KMSKeySecrets, foreign)
				if foreign.R == nil {
					foreign.R = &secretR{}
				}
				foreign.R.KMSKey = local
				break
			}
		}
	}

	return nil
}

// AddKeyVersions adds the given related objects to the existing relationships
// of the key, optionally inserting them as new records.
// Appends related to o.R.KeyVersions.
// Sets related.R.Key appropriately.
func (o *Key) AddKeyVersions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*KeyVersion) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.KeyID = o.KeyID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"key_versions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"key_id"}),
				strmangle.WhereClause("\"", "\"", 2, keyVersionPrimaryKeyColumns),
			)
			values := []interface{}{o.KeyID, rel.KeyID, rel.Version}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.KeyID = o.KeyID
		}
	}

	if o.R == nil {
		o.R = &keyR{
			KeyVersions: related,
		}
	} else {
		o.R.KeyVersions = append(o.R.KeyVersions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &keyVersionR{
				Key: o,
			}
		} else {
			rel.R.Key = o
		}
	}
	return nil
}

// AddKMSKeySecrets adds the given related objects to the existing relationships
// of the key, optionally inserting them as new records.
// Appends related to o.R.KMSKeySecrets.
// Sets related.R.KMSKey appropriately.
func (o *Key) AddKMSKeySecrets(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Secret) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.KMSKeyID = o.KeyID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"secrets\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"kms_key_id"}),
				strmangle.WhereClause("\"", "\"", 2, secretPrimaryKeyColumns),
			)
			values := []interface{}{o.KeyID, rel.KeyID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.KMSKeyID = o.KeyID
		}
	}

	if o.R == nil {
		o.R = &keyR{
			KMSKeySecrets: related,
		}
	} else {
		o.R.KMSKeySecrets = append(o.R.KMSKeySecrets, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &secretR{
				KMSKey: o,
			}
		} else {
			rel.R.KMSKey = o
		}
	}
	return nil
}

// Keys retrieves all the records using an executor.
func Keys(mods ...qm.QueryMod) keyQuery {
	mods = append(mods, qm.From("\"keys\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"keys\".*"})
	}

	return keyQuery{q}
}

// FindKey retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindKey(ctx context.Context, exec boil.ContextExecutor, keyID string, selectCols ...string) (*Key, error) {
	keyObj := &Key{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"keys\" where \"key_id\"=$1", sel,
	)

	q := queries.Raw(query, keyID)

	err := q.Bind(ctx, exec, keyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from keys")
	}

	return keyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Key) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no keys provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(keyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	keyInsertCacheMut.RLock()
	cache, cached := keyInsertCache[key]
	keyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			keyAllColumns,
			keyColumnsWithDefault,
			keyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(keyType, keyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(keyType, keyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"keys\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"keys\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into keys")
	}

	if !cached {
		keyInsertCacheMut.Lock()
		keyInsertCache[key] = cache
		keyInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Key.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Key) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	keyUpdateCacheMut.RLock()
	cache, cached := keyUpdateCache[key]
	keyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			keyAllColumns,
			keyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update keys, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"keys\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, keyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(keyType, keyMapping, append(wl, keyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update keys row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for keys")
	}

	if !cached {
		keyUpdateCacheMut.Lock()
		keyUpdateCache[key] = cache
		keyUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q keyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for keys")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o KeySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, keyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in key slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all key")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Key) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no keys provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(keyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	keyUpsertCacheMut.RLock()
	cache, cached := keyUpsertCache[key]
	keyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			keyAllColumns,
			keyColumnsWithDefault,
			keyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			keyAllColumns,
			keyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert keys, could not build update column list")
		}

		ret := strmangle.SetComplement(keyAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(keyPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert keys, could not build conflict column list")
			}

			conflict = make([]string, len(keyPrimaryKeyColumns))
			copy(conflict, keyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"keys\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(keyType, keyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(keyType, keyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert keys")
	}

	if !cached {
		keyUpsertCacheMut.Lock()
		keyUpsertCache[key] = cache
		keyUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Key record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Key) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Key provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), keyPrimaryKeyMapping)
	sql := "DELETE FROM \"keys\" WHERE \"key_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for keys")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q keyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no keyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for keys")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o KeySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, keyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from key slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for keys")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Key) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindKey(ctx, exec, o.KeyID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *KeySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := KeySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"keys\".* FROM \"keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, keyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in KeySlice")
	}

	*o = slice

	return nil
}

// KeyExists checks if the Key row exists.
func KeyExists(ctx context.Context, exec boil.ContextExecutor, keyID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"keys\" where \"key_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, keyID)
	}
	row := exec.QueryRowContext(ctx, sql, keyID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if keys exists")
	}

	return exists, nil
}

// Exists checks if the Key row exists.
func (o *Key) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return KeyExists(ctx, exec, o.KeyID)
}
