// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensUpsert)

	t.Run("AppUserProfiles", testAppUserProfilesUpsert)

	t.Run("AuditLogs", testAuditLogsUpsert)

	t.Run("ConfirmationTokens", testConfirmationTokensUpsert)

	t.Run("KeyVersions", testKeyVersionsUpsert)

	t.Run("Keys", testKeysUpsert)

	t.Run("PasswordResetTokens", testPasswordResetTokensUpsert)

	t.Run("Policies", testPoliciesUpsert)

	t.Run("PushTokens", testPushTokensUpsert)

	t.Run("RefreshTokens", testRefreshTokensUpsert)

	t.Run("Secrets", testSecretsUpsert)

	t.Run("Users", testUsersUpsert)
}
