// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSecrets(t *testing.T) {
	t.Parallel()

	query := Secrets()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSecretsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSecretsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Secrets().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSecretsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SecretSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSecretsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SecretExists(ctx, tx, o.KeyID)
	if err != nil {
		t.Errorf("Unable to check if Secret exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SecretExists to return true, but got false.")
	}
}

func testSecretsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	secretFound, err := FindSecret(ctx, tx, o.KeyID)
	if err != nil {
		t.Error(err)
	}

	if secretFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSecretsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Secrets().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSecretsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Secrets().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSecretsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	secretOne := &Secret{}
	secretTwo := &Secret{}
	if err = randomize.Struct(seed, secretOne, secretDBTypes, false, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}
	if err = randomize.Struct(seed, secretTwo, secretDBTypes, false, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = secretOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = secretTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Secrets().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSecretsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	secretOne := &Secret{}
	secretTwo := &Secret{}
	if err = randomize.Struct(seed, secretOne, secretDBTypes, false, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}
	if err = randomize.Struct(seed, secretTwo, secretDBTypes, false, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = secretOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = secretTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testSecretsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSecretsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(secretPrimaryKeyColumns, secretColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSecretToOneKeyUsingKMSKey(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Secret
	var foreign Key

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, secretDBTypes, false, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, keyDBTypes, false, keyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Key struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.KMSKeyID = foreign.KeyID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.KMSKey().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.KeyID != foreign.KeyID {
		t.Errorf("want: %v, got %v", foreign.KeyID, check.KeyID)
	}

	slice := SecretSlice{&local}
	if err = local.L.LoadKMSKey(ctx, tx, false, (*[]*Secret)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.KMSKey == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.KMSKey = nil
	if err = local.L.LoadKMSKey(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.KMSKey == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testSecretToOneSetOpKeyUsingKMSKey(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Secret
	var b, c Key

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, secretDBTypes, false, strmangle.SetComplement(secretPrimaryKeyColumns, secretColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, keyDBTypes, false, strmangle.SetComplement(keyPrimaryKeyColumns, keyColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, keyDBTypes, false, strmangle.SetComplement(keyPrimaryKeyColumns, keyColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Key{&b, &c} {
		err = a.SetKMSKey(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.KMSKey != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.KMSKeySecrets[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.KMSKeyID != x.KeyID {
			t.Error("foreign key was wrong value", a.KMSKeyID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.KMSKeyID))
		reflect.Indirect(reflect.ValueOf(&a.KMSKeyID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.KMSKeyID != x.KeyID {
			t.Error("foreign key was wrong value", a.KMSKeyID, x.KeyID)
		}
	}
}

func testSecretsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSecretsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SecretSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSecretsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Secrets().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	secretDBTypes = map[string]string{`KeyID`: `character varying`, `EncryptedData`: `bytea`, `KMSKeyID`: `character varying`, `KeyVersion`: `integer`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_             = bytes.MinRead
)

func testSecretsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(secretPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(secretAllColumns) == len(secretPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, secretDBTypes, true, secretPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSecretsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(secretAllColumns) == len(secretPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, secretDBTypes, true, secretPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(secretAllColumns, secretPrimaryKeyColumns) {
		fields = secretAllColumns
	} else {
		fields = strmangle.SetComplement(
			secretAllColumns,
			secretPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SecretSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSecretsUpsert(t *testing.T) {
	t.Parallel()

	if len(secretAllColumns) == len(secretPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Secret{}
	if err = randomize.Struct(seed, &o, secretDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Secret: %s", err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, secretDBTypes, false, secretPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Secret: %s", err)
	}

	count, err = Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
