// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Secret is an object representing the database table.
type Secret struct {
	KeyID         string    `boil:"key_id" json:"key_id" toml:"key_id" yaml:"key_id"`
	EncryptedData []byte    `boil:"encrypted_data" json:"encrypted_data" toml:"encrypted_data" yaml:"encrypted_data"`
	KMSKeyID      string    `boil:"kms_key_id" json:"kms_key_id" toml:"kms_key_id" yaml:"kms_key_id"`
	KeyVersion    int       `boil:"key_version" json:"key_version" toml:"key_version" yaml:"key_version"`
	CreatedAt     time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *secretR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L secretL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SecretColumns = struct {
	KeyID         string
	EncryptedData string
	KMSKeyID      string
	KeyVersion    string
	CreatedAt     string
	UpdatedAt     string
}{
	KeyID:         "key_id",
	EncryptedData: "encrypted_data",
	KMSKeyID:      "kms_key_id",
	KeyVersion:    "key_version",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var SecretTableColumns = struct {
	KeyID         string
	EncryptedData string
	KMSKeyID      string
	KeyVersion    string
	CreatedAt     string
	UpdatedAt     string
}{
	KeyID:         "secrets.key_id",
	EncryptedData: "secrets.encrypted_data",
	KMSKeyID:      "secrets.kms_key_id",
	KeyVersion:    "secrets.key_version",
	CreatedAt:     "secrets.created_at",
	UpdatedAt:     "secrets.updated_at",
}

// Generated where

type whereHelper__byte struct{ field string }

func (w whereHelper__byte) EQ(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelper__byte) NEQ(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelper__byte) LT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelper__byte) LTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelper__byte) GT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelper__byte) GTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var SecretWhere = struct {
	KeyID         whereHelperstring
	EncryptedData whereHelper__byte
	KMSKeyID      whereHelperstring
	KeyVersion    whereHelperint
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
}{
	KeyID:         whereHelperstring{field: "\"secrets\".\"key_id\""},
	EncryptedData: whereHelper__byte{field: "\"secrets\".\"encrypted_data\""},
	KMSKeyID:      whereHelperstring{field: "\"secrets\".\"kms_key_id\""},
	KeyVersion:    whereHelperint{field: "\"secrets\".\"key_version\""},
	CreatedAt:     whereHelpertime_Time{field: "\"secrets\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"secrets\".\"updated_at\""},
}

// SecretRels is where relationship names are stored.
var SecretRels = struct {
	KMSKey string
}{
	KMSKey: "KMSKey",
}

// secretR is where relationships are stored.
type secretR struct {
	KMSKey *Key `boil:"KMSKey" json:"KMSKey" toml:"KMSKey" yaml:"KMSKey"`
}

// NewStruct creates a new relationship struct
func (*secretR) NewStruct() *secretR {
	return &secretR{}
}

func (o *Secret) GetKMSKey() *Key {
	if o == nil {
		return nil
	}

	return o.R.GetKMSKey()
}

func (r *secretR) GetKMSKey() *Key {
	if r == nil {
		return nil
	}

	return r.KMSKey
}

// secretL is where Load methods for each relationship are stored.
type secretL struct{}

var (
	secretAllColumns            = []string{"key_id", "encrypted_data", "kms_key_id", "key_version", "created_at", "updated_at"}
	secretColumnsWithoutDefault = []string{"key_id", "encrypted_data", "kms_key_id", "key_version"}
	secretColumnsWithDefault    = []string{"created_at", "updated_at"}
	secretPrimaryKeyColumns     = []string{"key_id"}
	secretGeneratedColumns      = []string{}
)

type (
	// SecretSlice is an alias for a slice of pointers to Secret.
	// This should almost always be used instead of []Secret.
	SecretSlice []*Secret

	secretQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	secretType                 = reflect.TypeOf(&Secret{})
	secretMapping              = queries.MakeStructMapping(secretType)
	secretPrimaryKeyMapping, _ = queries.BindMapping(secretType, secretMapping, secretPrimaryKeyColumns)
	secretInsertCacheMut       sync.RWMutex
	secretInsertCache          = make(map[string]insertCache)
	secretUpdateCacheMut       sync.RWMutex
	secretUpdateCache          = make(map[string]updateCache)
	secretUpsertCacheMut       sync.RWMutex
	secretUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single secret record from the query.
func (q secretQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Secret, error) {
	o := &Secret{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for secrets")
	}

	return o, nil
}

// All returns all Secret records from the query.
func (q secretQuery) All(ctx context.Context, exec boil.ContextExecutor) (SecretSlice, error) {
	var o []*Secret

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Secret slice")
	}

	return o, nil
}

// Count returns the count of all Secret records in the query.
func (q secretQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count secrets rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q secretQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if secrets exists")
	}

	return count > 0, nil
}

// KMSKey pointed to by the foreign key.
func (o *Secret) KMSKey(mods ...qm.QueryMod) keyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"key_id\" = ?", o.KMSKeyID),
	}

	queryMods = append(queryMods, mods...)

	return Keys(queryMods...)
}

// LoadKMSKey allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (secretL) LoadKMSKey(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSecret interface{}, mods queries.Applicator) error {
	var slice []*Secret
	var object *Secret

	if singular {
		var ok bool
		object, ok = maybeSecret.(*Secret)
		if !ok {
			object = new(Secret)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSecret)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSecret))
			}
		}
	} else {
		s, ok := maybeSecret.(*[]*Secret)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSecret)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSecret))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &secretR{}
		}
		args[object.KMSKeyID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &secretR{}
			}

			args[obj.KMSKeyID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`keys`),
		qm.WhereIn(`keys.key_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Key")
	}

	var resultSlice []*Key
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Key")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for keys")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for keys")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.KMSKey = foreign
		if foreign.R == nil {
			foreign.R = &keyR{}
		}
		foreign.R.KMSKeySecrets = append(foreign.R.KMSKeySecrets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.KMSKeyID == foreign.KeyID {
				local.R.KMSKey = foreign
				if foreign.R == nil {
					foreign.R = &keyR{}
				}
				foreign.R.KMSKeySecrets = append(foreign.R.KMSKeySecrets, local)
				break
			}
		}
	}

	return nil
}

// SetKMSKey of the secret to the related item.
// Sets o.R.KMSKey to related.
// Adds o to related.R.KMSKeySecrets.
func (o *Secret) SetKMSKey(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Key) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"secrets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"kms_key_id"}),
		strmangle.WhereClause("\"", "\"", 2, secretPrimaryKeyColumns),
	)
	values := []interface{}{related.KeyID, o.KeyID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.KMSKeyID = related.KeyID
	if o.R == nil {
		o.R = &secretR{
			KMSKey: related,
		}
	} else {
		o.R.KMSKey = related
	}

	if related.R == nil {
		related.R = &keyR{
			KMSKeySecrets: SecretSlice{o},
		}
	} else {
		related.R.KMSKeySecrets = append(related.R.KMSKeySecrets, o)
	}

	return nil
}

// Secrets retrieves all the records using an executor.
func Secrets(mods ...qm.QueryMod) secretQuery {
	mods = append(mods, qm.From("\"secrets\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"secrets\".*"})
	}

	return secretQuery{q}
}

// FindSecret retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSecret(ctx context.Context, exec boil.ContextExecutor, keyID string, selectCols ...string) (*Secret, error) {
	secretObj := &Secret{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"secrets\" where \"key_id\"=$1", sel,
	)

	q := queries.Raw(query, keyID)

	err := q.Bind(ctx, exec, secretObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from secrets")
	}

	return secretObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Secret) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no secrets provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(secretColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	secretInsertCacheMut.RLock()
	cache, cached := secretInsertCache[key]
	secretInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			secretAllColumns,
			secretColumnsWithDefault,
			secretColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(secretType, secretMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(secretType, secretMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"secrets\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"secrets\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into secrets")
	}

	if !cached {
		secretInsertCacheMut.Lock()
		secretInsertCache[key] = cache
		secretInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Secret.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Secret) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	secretUpdateCacheMut.RLock()
	cache, cached := secretUpdateCache[key]
	secretUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			secretAllColumns,
			secretPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update secrets, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"secrets\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, secretPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(secretType, secretMapping, append(wl, secretPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update secrets row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for secrets")
	}

	if !cached {
		secretUpdateCacheMut.Lock()
		secretUpdateCache[key] = cache
		secretUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q secretQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for secrets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for secrets")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SecretSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), secretPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"secrets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, secretPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in secret slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all secret")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Secret) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no secrets provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(secretColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	secretUpsertCacheMut.RLock()
	cache, cached := secretUpsertCache[key]
	secretUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			secretAllColumns,
			secretColumnsWithDefault,
			secretColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			secretAllColumns,
			secretPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert secrets, could not build update column list")
		}

		ret := strmangle.SetComplement(secretAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(secretPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert secrets, could not build conflict column list")
			}

			conflict = make([]string, len(secretPrimaryKeyColumns))
			copy(conflict, secretPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"secrets\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(secretType, secretMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(secretType, secretMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert secrets")
	}

	if !cached {
		secretUpsertCacheMut.Lock()
		secretUpsertCache[key] = cache
		secretUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Secret record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Secret) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Secret provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), secretPrimaryKeyMapping)
	sql := "DELETE FROM \"secrets\" WHERE \"key_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from secrets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for secrets")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q secretQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no secretQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from secrets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for secrets")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SecretSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), secretPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"secrets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, secretPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from secret slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for secrets")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Secret) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSecret(ctx, exec, o.KeyID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SecretSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SecretSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), secretPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"secrets\".* FROM \"secrets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, secretPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SecretSlice")
	}

	*o = slice

	return nil
}

// SecretExists checks if the Secret row exists.
func SecretExists(ctx context.Context, exec boil.ContextExecutor, keyID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"secrets\" where \"key_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, keyID)
	}
	row := exec.QueryRowContext(ctx, sql, keyID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if secrets exists")
	}

	return exists, nil
}

// Exists checks if the Secret row exists.
func (o *Secret) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SecretExists(ctx, exec, o.KeyID)
}
