// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/kashguard/go-kms/internal/auth"
	"github.com/kashguard/go-kms/internal/config"
	"github.com/kashguard/go-kms/internal/data/local"
	"github.com/kashguard/go-kms/internal/metrics"
	"testing"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitNewServer returns a new Server instance.
func InitNewServer(server config.Server) (*Server, error) {
	db, err := NewDB(server)
	if err != nil {
		return nil, err
	}
	mailer, err := NewMailer(server)
	if err != nil {
		return nil, err
	}
	service, err := NewPush(server, db)
	if err != nil {
		return nil, err
	}
	i18nService, err := NewI18N(server)
	if err != nil {
		return nil, err
	}
	v := NoTest()
	clock := NewClock(v...)
	authService := NewAuthService(server, db, clock)
	localService := local.NewService(server, db, clock)
	metricsService, err := metrics.New(server, db)
	if err != nil {
		return nil, err
	}
	adapter, err := NewHSMAdapter(server, db)
	if err != nil {
		return nil, err
	}
	metadataStore, err := NewMetadataStore(server, db)
	if err != nil {
		return nil, err
	}
	engine := NewPolicyEngine(metadataStore)
	logger := NewAuditLogger(metadataStore)
	keyService, err := NewKeyService(db, adapter, metadataStore, engine, logger)
	if err != nil {
		return nil, err
	}
	encryptionService, err := NewEncryptionService(keyService, adapter, metadataStore, engine, logger)
	if err != nil {
		return nil, err
	}
	signService, err := NewSignService(keyService, adapter, metadataStore, engine, logger)
	if err != nil {
		return nil, err
	}
	secretService, err := NewSecretService(encryptionService, keyService, metadataStore, engine, logger, server)
	if err != nil {
		return nil, err
	}
	apiServer := newServerWithComponents(server, db, mailer, service, i18nService, clock, authService, localService, metricsService, keyService, encryptionService, signService, secretService, engine, logger, metadataStore)
	return apiServer, nil
}

// InitNewServerWithDB returns a new Server instance with the given DB instance.
// All the other components are initialized via go wire according to the configuration.
func InitNewServerWithDB(server config.Server, db *sql.DB, t ...*testing.T) (*Server, error) {
	mailer, err := NewMailer(server)
	if err != nil {
		return nil, err
	}
	service, err := NewPush(server, db)
	if err != nil {
		return nil, err
	}
	i18nService, err := NewI18N(server)
	if err != nil {
		return nil, err
	}
	clock := NewClock(t...)
	authService := NewAuthService(server, db, clock)
	localService := local.NewService(server, db, clock)
	metricsService, err := metrics.New(server, db)
	if err != nil {
		return nil, err
	}
	adapter, err := NewHSMAdapter(server, db)
	if err != nil {
		return nil, err
	}
	metadataStore, err := NewMetadataStore(server, db)
	if err != nil {
		return nil, err
	}
	engine := NewPolicyEngine(metadataStore)
	logger := NewAuditLogger(metadataStore)
	keyService, err := NewKeyService(db, adapter, metadataStore, engine, logger)
	if err != nil {
		return nil, err
	}
	encryptionService, err := NewEncryptionService(keyService, adapter, metadataStore, engine, logger)
	if err != nil {
		return nil, err
	}
	signService, err := NewSignService(keyService, adapter, metadataStore, engine, logger)
	if err != nil {
		return nil, err
	}
	secretService, err := NewSecretService(encryptionService, keyService, metadataStore, engine, logger, server)
	if err != nil {
		return nil, err
	}
	apiServer := newServerWithComponents(server, db, mailer, service, i18nService, clock, authService, localService, metricsService, keyService, encryptionService, signService, secretService, engine, logger, metadataStore)
	return apiServer, nil
}

// wire.go:

// serviceSet groups the default set of providers that are required for initing a server
var serviceSet = wire.NewSet(
	newServerWithComponents,
	NewPush,
	NewMailer,
	NewI18N,
	authServiceSet, local.NewService, metrics.New, NewClock,
	kmsServiceSet,
)

var kmsServiceSet = wire.NewSet(
	NewHSMAdapter,
	NewMetadataStore,
	NewPolicyEngine,
	NewAuditLogger,
	NewKeyService,
	NewEncryptionService,
	NewSignService,
	NewSecretService,
)

var authServiceSet = wire.NewSet(
	NewAuthService, wire.Bind(new(AuthService), new(*auth.Service)),
)
