#!/bin/bash
# SoftHSM 初始化脚本
# 用于在 Docker 容器中自动初始化 SoftHSM token

# 不要使用 set -e，因为某些命令可能失败但我们想继续执行
set +e

# 从环境变量获取配置，如果没有设置则使用默认值
HSM_SLOT=${KMS_HSM_SLOT:-0}
HSM_PIN=${KMS_HSM_PIN:-1234}
HSM_LABEL=${KMS_HSM_LABEL:-KMS}

# 创建 SoftHSM 配置目录
mkdir -p ~/.config/softhsm2

# 创建 SoftHSM 配置文件（如果不存在）
SOFTHSM_CONF="$HOME/.config/softhsm2/softhsm2.conf"
if [ ! -f "$SOFTHSM_CONF" ]; then
    echo "Creating SoftHSM configuration file..."
    # 创建数据库目录
    SOFTHSM_DB_DIR="$HOME/.config/softhsm2/tokens"
    mkdir -p "$SOFTHSM_DB_DIR"
    
    # 写入配置文件
    cat > "$SOFTHSM_CONF" <<EOF
# SoftHSM configuration file
# This file was automatically generated by init-softhsm.sh

directories.tokendir = $SOFTHSM_DB_DIR
objectstore.backend = file

# Logging
log.level = INFO
EOF
    echo "SoftHSM configuration file created at: $SOFTHSM_CONF"
    echo "Token directory: $SOFTHSM_DB_DIR"
else
    echo "Using existing SoftHSM configuration: $SOFTHSM_CONF"
fi

echo "Initializing SoftHSM token..."

# 检查 SoftHSM 是否已安装
if ! command -v softhsm2-util &> /dev/null; then
    echo "ERROR: softhsm2-util not found. Please install SoftHSM2:"
    echo "  apt-get update && apt-get install -y softhsm2"
    exit 1
fi

# 检查库文件是否存在，如果未设置则自动查找
if [ -z "$KMS_HSM_LIBRARY" ] || [ ! -f "$KMS_HSM_LIBRARY" ]; then
    echo "Searching for SoftHSM library..."
    # 尝试查找常见路径（优先使用自定义编译的版本）
    POSSIBLE_PATHS=(
        "/home/development/softhsm-ed25519/lib/softhsm/libsofthsm2.so"  # Custom-built with Ed25519 support
        "/opt/softhsm-ed25519/lib/softhsm/libsofthsm2.so"               # Alternative custom path
        "/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so"
        "/usr/lib/softhsm/libsofthsm2.so"
        "/usr/local/lib/softhsm/libsofthsm2.so"
        "/usr/lib/aarch64-linux-gnu/softhsm/libsofthsm2.so"
    )
    
    HSM_LIBRARY=""
    for path in "${POSSIBLE_PATHS[@]}"; do
        if [ -f "$path" ]; then
            HSM_LIBRARY="$path"
            echo "Found SoftHSM library at: $HSM_LIBRARY"
            break
        fi
    done
    
    if [ -z "$HSM_LIBRARY" ]; then
        echo "ERROR: SoftHSM library not found in any common location"
        echo "Searched paths:"
        for path in "${POSSIBLE_PATHS[@]}"; do
            echo "  - $path"
        done
        echo ""
        echo "Please install SoftHSM2: apt-get update && apt-get install -y softhsm2"
        echo "Or set KMS_HSM_LIBRARY to the correct library path"
        exit 1
    fi
    
    # 将找到的库路径写入文件，供应用启动时读取
    echo "$HSM_LIBRARY" > /tmp/kms_hsm_library
    echo "Using SoftHSM library: $HSM_LIBRARY"
    echo "Library path saved to /tmp/kms_hsm_library"
else
    HSM_LIBRARY="$KMS_HSM_LIBRARY"
    echo "Using configured SoftHSM library: $HSM_LIBRARY"
    # 也将配置的路径写入文件
    echo "$HSM_LIBRARY" > /tmp/kms_hsm_library
fi

# 显示当前 slots
echo "Checking SoftHSM slots..."
SLOTS_OUTPUT=$(softhsm2-util --show-slots 2>&1)
SLOTS_EXIT_CODE=$?

if [ $SLOTS_EXIT_CODE -eq 0 ]; then
    echo "$SLOTS_OUTPUT"
    echo ""
else
    echo "WARNING: Failed to show slots: $SLOTS_OUTPUT"
    echo ""
fi

# 首先检查是否已经有 label 为 $HSM_LABEL 的已初始化 token
EXISTING_TOKEN_SLOT=""
if [ $SLOTS_EXIT_CODE -eq 0 ]; then
    # 查找带有指定 label 且已初始化的 token
    while IFS= read -r line; do
        if echo "$line" | grep -q "Slot [0-9]"; then
            CURRENT_SLOT=$(echo "$line" | sed 's/.*Slot \([0-9]*\).*/\1/')
        elif echo "$line" | grep -q "Label:.*$HSM_LABEL"; then
            # 检查这个 slot 的 token 是否已初始化
            SLOT_SECTION=$(echo "$SLOTS_OUTPUT" | sed -n "/Slot $CURRENT_SLOT/,/^$/p")
            if echo "$SLOT_SECTION" | grep -q "Initialized.*yes"; then
                EXISTING_TOKEN_SLOT="$CURRENT_SLOT"
                break
            fi
        fi
    done <<< "$SLOTS_OUTPUT"
fi

# 如果找到了已存在的 token，直接使用
if [ -n "$EXISTING_TOKEN_SLOT" ]; then
    echo "✓ Found existing initialized token with label '$HSM_LABEL' in slot $EXISTING_TOKEN_SLOT"
    HSM_SLOT="$EXISTING_TOKEN_SLOT"
    SLOT_EXISTS=true
    TOKEN_EXISTS=true
    TOKEN_INITIALIZED=true
else
    # 检查指定的 slot 是否已存在 token，以及 token 是否已初始化
    SLOT_EXISTS=false
    TOKEN_EXISTS=false
    TOKEN_INITIALIZED=false

    if [ $SLOTS_EXIT_CODE -eq 0 ]; then
        # 检查 slot 是否存在
        if echo "$SLOTS_OUTPUT" | grep -q "Slot $HSM_SLOT"; then
            SLOT_EXISTS=true
            # 检查该 slot 是否有 token
            SLOT_INFO=$(echo "$SLOTS_OUTPUT" | sed -n "/Slot $HSM_SLOT/,/^$/p")
            if echo "$SLOT_INFO" | grep -q "Token present.*yes"; then
                TOKEN_EXISTS=true
                # 检查 token 是否已初始化
                if echo "$SLOT_INFO" | grep -q "Initialized.*yes"; then
                    TOKEN_INITIALIZED=true
                    echo "✓ Token already exists and is initialized in slot $HSM_SLOT"
                else
                    echo "⚠ Token exists in slot $HSM_SLOT but is NOT initialized"
                    echo "  Will initialize the token..."
                fi
            else
                echo "Slot $HSM_SLOT exists but has no token"
            fi
        else
            echo "Slot $HSM_SLOT does not exist"
        fi
    fi
fi

# 如果 token 不存在或未初始化，则尝试初始化
if [ "$TOKEN_EXISTS" = false ] || [ "$TOKEN_INITIALIZED" = false ]; then
    if [ "$TOKEN_EXISTS" = false ]; then
        if [ "$SLOT_EXISTS" = false ]; then
            echo "Initializing new token in slot $HSM_SLOT..."
        else
            echo "Initializing token in existing slot $HSM_SLOT..."
        fi
    else
        echo "Initializing uninitialized token in slot $HSM_SLOT..."
    fi
    
    INIT_OUTPUT=$(softhsm2-util --init-token --slot "$HSM_SLOT" --label "$HSM_LABEL" --pin "$HSM_PIN" --so-pin "$HSM_PIN" 2>&1)
    INIT_EXIT_CODE=$?
    
    if [ $INIT_EXIT_CODE -eq 0 ]; then
        echo "✓ SoftHSM token initialized successfully"
        TOKEN_EXISTS=true
        TOKEN_INITIALIZED=true
        
        # 重新获取 slots 信息，找到实际分配的 slot ID（可能是内部 slot ID）
        echo "Detecting actual slot ID for initialized token..."
        NEW_SLOTS_OUTPUT=$(softhsm2-util --show-slots 2>&1)
        if [ $? -eq 0 ]; then
            # 查找带有指定 label 的 token 的实际 slot ID
            ACTUAL_SLOT=$(echo "$NEW_SLOTS_OUTPUT" | grep -B 5 "Label:.*$HSM_LABEL" | grep "Slot" | head -1 | sed 's/.*Slot \([0-9]*\).*/\1/')
            if [ -n "$ACTUAL_SLOT" ] && [ "$ACTUAL_SLOT" != "$HSM_SLOT" ]; then
                echo "Token was initialized in slot $ACTUAL_SLOT (not $HSM_SLOT)"
                HSM_SLOT="$ACTUAL_SLOT"
            else
                echo "Token initialized in slot $HSM_SLOT"
            fi
        fi
    else
        echo "WARNING: Failed to initialize token in slot $HSM_SLOT"
        echo "Error output: $INIT_OUTPUT"
        
        # 如果初始化失败，尝试使用 --free 选项（如果 slot 被占用）
        if echo "$INIT_OUTPUT" | grep -q "CKR_SLOT_ID_INVALID\|CKR_TOKEN_NOT_PRESENT"; then
            echo "Trying to create token without specifying slot (auto-assign)..."
            AUTO_INIT_OUTPUT=$(softhsm2-util --init-token --free --label "$HSM_LABEL" --pin "$HSM_PIN" --so-pin "$HSM_PIN" 2>&1)
            if [ $? -eq 0 ]; then
                echo "✓ Token initialized in auto-assigned slot"
                # 等待一下让系统更新
                sleep 1
                # 获取新创建的 slot
                NEW_SLOTS_OUTPUT=$(softhsm2-util --show-slots 2>&1)
                # 查找带有指定 label 的 slot
                ACTUAL_SLOT=""
                while IFS= read -r line; do
                    if echo "$line" | grep -q "Slot [0-9]"; then
                        CURRENT_SLOT=$(echo "$line" | sed 's/.*Slot \([0-9]*\).*/\1/')
                    elif echo "$line" | grep -q "Label:.*$HSM_LABEL"; then
                        # 验证这个 slot 的 token 已初始化
                        SLOT_SECTION=$(echo "$NEW_SLOTS_OUTPUT" | sed -n "/Slot $CURRENT_SLOT/,/^$/p")
                        if echo "$SLOT_SECTION" | grep -q "Initialized.*yes"; then
                            ACTUAL_SLOT="$CURRENT_SLOT"
                            break
                        fi
                    fi
                done <<< "$NEW_SLOTS_OUTPUT"
                
                if [ -n "$ACTUAL_SLOT" ]; then
                    HSM_SLOT="$ACTUAL_SLOT"
                    echo "New token created in slot $HSM_SLOT"
                    TOKEN_EXISTS=true
                    TOKEN_INITIALIZED=true
                else
                    echo "WARNING: Token initialized but could not detect slot ID"
                fi
            else
                echo "Failed to auto-initialize token: $AUTO_INIT_OUTPUT"
            fi
        fi
    fi
fi

# 如果仍然没有已初始化的 token，尝试使用第一个已初始化的 slot
if [ "$TOKEN_INITIALIZED" = false ]; then
    # 重新获取最新的 slots 信息
    LATEST_SLOTS_OUTPUT=$(softhsm2-util --show-slots 2>&1)
    if [ $? -eq 0 ]; then
        echo "Attempting to use first available initialized token..."
        # 查找第一个已初始化的 token（通过 Label 匹配或 Initialized: yes）
        FIRST_INIT_SLOT=$(echo "$LATEST_SLOTS_OUTPUT" | grep -B 10 "Initialized.*yes" | grep "Slot" | head -1 | sed 's/.*Slot \([0-9]*\).*/\1/')
        if [ -n "$FIRST_INIT_SLOT" ]; then
            echo "Using initialized token in slot $FIRST_INIT_SLOT"
            HSM_SLOT="$FIRST_INIT_SLOT"
            TOKEN_EXISTS=true
            TOKEN_INITIALIZED=true
        else
            echo "ERROR: No initialized token found. Please initialize a token manually:"
            echo "  softhsm2-util --init-token --slot $HSM_SLOT --label '$HSM_LABEL' --pin $HSM_PIN --so-pin $HSM_PIN"
            exit 1
        fi
    else
        echo "ERROR: Failed to query slots. Cannot determine token status."
        exit 1
    fi
fi

# 最终验证：确保我们使用的 slot 确实有已初始化的 token
FINAL_SLOTS_OUTPUT=$(softhsm2-util --show-slots 2>&1)
if [ $? -eq 0 ]; then
    SLOT_INFO=$(echo "$FINAL_SLOTS_OUTPUT" | sed -n "/Slot $HSM_SLOT/,/^$/p")
    if echo "$SLOT_INFO" | grep -q "Initialized.*yes"; then
        # 检查 label 是否匹配
        if echo "$SLOT_INFO" | grep -q "Label:.*$HSM_LABEL"; then
            echo "✓ Verified: Slot $HSM_SLOT has an initialized token with label '$HSM_LABEL'"
        else
            ACTUAL_LABEL=$(echo "$SLOT_INFO" | grep "Label:" | sed 's/.*Label:[[:space:]]*\(.*\)/\1/' | xargs)
            echo "✓ Verified: Slot $HSM_SLOT has an initialized token (label: '$ACTUAL_LABEL')"
        fi
    else
        echo "WARNING: Slot $HSM_SLOT may not have an initialized token"
        # 尝试通过 label 找到正确的 slot
        CORRECT_SLOT=""
        CURRENT_SLOT=""
        while IFS= read -r line; do
            if echo "$line" | grep -q "Slot [0-9]"; then
                CURRENT_SLOT=$(echo "$line" | sed 's/.*Slot \([0-9]*\).*/\1/')
            elif echo "$line" | grep -q "Label:.*$HSM_LABEL"; then
                SLOT_SECTION=$(echo "$FINAL_SLOTS_OUTPUT" | sed -n "/Slot $CURRENT_SLOT/,/^$/p")
                if echo "$SLOT_SECTION" | grep -q "Initialized.*yes"; then
                    CORRECT_SLOT="$CURRENT_SLOT"
                    break
                fi
            fi
        done <<< "$FINAL_SLOTS_OUTPUT"
        
        if [ -n "$CORRECT_SLOT" ] && [ "$CORRECT_SLOT" != "$HSM_SLOT" ]; then
            echo "Found token with label '$HSM_LABEL' in slot $CORRECT_SLOT"
            HSM_SLOT="$CORRECT_SLOT"
        fi
    fi
fi

# 保存实际使用的 slot 到文件（供应用读取）
echo "$HSM_SLOT" > /tmp/kms_hsm_slot
echo "Using slot: $HSM_SLOT"

# 显示最终状态
echo ""
echo "Final SoftHSM slots status:"
if softhsm2-util --show-slots 2>&1; then
    echo ""
else
    echo "WARNING: Failed to show final slots status"
    echo ""
fi

echo ""
echo "SoftHSM initialization complete!"
echo "  Slot: $HSM_SLOT"
echo "  Label: $HSM_LABEL"
echo "  PIN: $HSM_PIN"
echo "  Library: $HSM_LIBRARY"

