// Code generated by go run -tags scripts scripts/handlers/gen_handlers.go; DO NOT EDIT.
package handlers

import (
	"github.com/kashguard/go-kms/internal/api"
	"github.com/kashguard/go-kms/internal/api/handlers/auth"
	"github.com/kashguard/go-kms/internal/api/handlers/common"
	"github.com/kashguard/go-kms/internal/api/handlers/kms/audit"
	"github.com/kashguard/go-kms/internal/api/handlers/kms/encryption"
	"github.com/kashguard/go-kms/internal/api/handlers/kms/keys"
	"github.com/kashguard/go-kms/internal/api/handlers/kms/policies"
	"github.com/kashguard/go-kms/internal/api/handlers/kms/secrets"
	"github.com/kashguard/go-kms/internal/api/handlers/kms/sign"
	"github.com/kashguard/go-kms/internal/api/handlers/push"
	"github.com/kashguard/go-kms/internal/api/handlers/wellknown"
	"github.com/labstack/echo/v4"
)

func AttachAllRoutes(s *api.Server) {
	// attach our routes
	s.Router.Routes = []*echo.Route{
		auth.DeleteUserAccountRoute(s),
		auth.GetCompleteRegisterRoute(s),
		auth.GetUserInfoRoute(s),
		auth.PostChangePasswordRoute(s),
		auth.PostCompleteRegisterRoute(s),
		auth.PostForgotPasswordCompleteRoute(s),
		auth.PostForgotPasswordRoute(s),
		auth.PostLoginRoute(s),
		auth.PostLogoutRoute(s),
		auth.PostRefreshRoute(s),
		auth.PostRegisterRoute(s),
		common.GetHealthyRoute(s),
		common.GetReadyRoute(s),
		common.GetSwaggerRoute(s),
		common.GetVersionRoute(s),
		audit.GetAuditLogsRoute(s),
		encryption.PostDecryptRoute(s),
		encryption.PostEncryptRoute(s),
		encryption.PostGenerateDataKeyRoute(s),
		keys.DeleteKeyRoute(s),
		keys.GetKeyRoute(s),
		keys.GetListKeysRoute(s),
		keys.PostCreateKeyRoute(s),
		keys.PostDisableKeyRoute(s),
		keys.PostEnableKeyRoute(s),
		keys.PostRotateKeyRoute(s),
		keys.PutUpdateKeyRoute(s),
		policies.DeletePolicyRoute(s),
		policies.GetListPoliciesRoute(s),
		policies.GetPolicyRoute(s),
		policies.PostCreatePolicyRoute(s),
		policies.PutUpdatePolicyRoute(s),
		secrets.DeleteSecretRoute(s),
		secrets.GetSecretRoute(s),
		secrets.HeadSecretExistsRoute(s),
		secrets.PostCreateSecretRoute(s),
		secrets.PutUpdateSecretRoute(s),
		sign.PostSignRoute(s),
		sign.PostVerifyRoute(s),
		push.PutUpdatePushTokenRoute(s),
		wellknown.GetAndroidDigitalAssetLinksRoute(s),
		wellknown.GetAppleAppSiteAssociationRoute(s),
	}
}
